package com.sba.nutricanbe.diet.config;

import com.sba.nutricanbe.diet.entity.FoodItem;
import com.sba.nutricanbe.diet.repository.FoodItemRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

@Slf4j
@Component
@Order(10)
@RequiredArgsConstructor
public class FoodCatalogDataInitializer implements CommandLineRunner {

    private static final String SOURCE = "VTN_FCT_2007";

    private final FoodItemRepository foodItemRepository;

    @Override
    @Transactional
    public void run(String... args) {
        if (foodItemRepository.existsBySource(SOURCE)) {
            log.debug("Food catalog source {} already present, skipping VTN seed", SOURCE);
            return;
        }
        List<FoodItem> items = buildVtnFct2007Foods();
        foodItemRepository.saveAll(items);
        log.info("Seeded {} VTN_FCT_2007 food items", items.size());
    }

    private static List<FoodItem> buildVtnFct2007Foods() {
        List<FoodItem> items = new ArrayList<>();
        items.add(food("Gạo nếp cái", "Glutinous rice, milled", "Ngũ cốc và sản phẩm chế biến", List.of("gao nep cai", "glutinous rice, milled"), 344, 8.6, 74.5, 1.5));
        items.add(food("Gạo nếp máy (Loại thường)", "Glutinous rice, milled", "Ngũ cốc và sản phẩm chế biến", List.of("gao nep may (loai thuong)", "glutinous rice, milled"), 346, 8.4, 74.9, 1.6));
        items.add(food("Gạo tẻ giã", "Under milled, home-pounded rice", "Ngũ cốc và sản phẩm chế biến", List.of("gao te gia", "under milled, home-pounded rice"), 344, 8.1, 75.0, 1.3));
        items.add(food("Gạo tẻ máy", "Ordinary polished rice", "Ngũ cốc và sản phẩm chế biến", List.of("gao te may", "ordinary polished rice"), 344, 7.9, 75.9, 1.0));
        items.add(food("Gạo lứt", "Rice, brown or hulled", "Ngũ cốc và sản phẩm chế biến", List.of("gao lut", "rice, brown or hulled"), 345, 7.5, 72.8, 2.7));
        items.add(food("Kê", "Foxtail millet", "Ngũ cốc và sản phẩm chế biến", List.of("ke", "foxtail millet"), 331, 7.0, 69.0, 3.0));
        items.add(food("Ngô bắp tươi", "Fresh maize seeds, raw", "Ngũ cốc và sản phẩm chế biến", List.of("ngo bap tuoi", "fresh maize seeds, raw"), 196, 4.1, 39.6, 2.3));
        items.add(food("Ngô vàng hạt khô", "Yellow maize, dried seeds", "Ngũ cốc và sản phẩm chế biến", List.of("ngo vang hat kho", "yellow maize, dried seeds"), 354, 8.6, 69.4, 4.7));
        items.add(food("Bánh bao nhân thịt", "Ball shaped dumpling, Vietnamese steamed buns", "Ngũ cốc và sản phẩm chế biến", List.of("banh bao nhan thit", "ball shaped dumpling, vietnamese steamed buns"), 219, 6.1, 47.5, 0.5));
        items.add(food("Bánh đa nem", "Rice paper for rollers", "Ngũ cốc và sản phẩm chế biến", List.of("banh đa nem", "rice paper for rollers"), 333, 4.0, 78.9, 0.2));
        items.add(food("Bánh đúc", "Rice pudding", "Ngũ cốc và sản phẩm chế biến", List.of("banh đuc", "rice pudding"), 52, 0.9, 11.3, 0.3));
        items.add(food("Bánh mỳ", "French bread", "Ngũ cốc và sản phẩm chế biến", List.of("banh my", "french bread"), 249, 7.9, 52.6, 0.8));
        items.add(food("Bánh phở", "Rice noodles", "Ngũ cốc và sản phẩm chế biến", List.of("banh pho", "rice noodles"), 143, 3.2, 31.7, 0.4));
        items.add(food("Bánh quẩy", "Wheat fritters twisted fried", "Ngũ cốc và sản phẩm chế biến", List.of("banh quay", "wheat fritters twisted fried"), 292, 8.0, 40.7, 10.8));
        items.add(food("Bỏng ngô", "Corn flakes", "Ngũ cốc và sản phẩm chế biến", List.of("bong ngo", "corn flakes"), 372, 8.6, 80.8, 1.6));
        items.add(food("Bột gạo nếp", "Glutinous rice flour", "Ngũ cốc và sản phẩm chế biến", List.of("bot gao nep", "glutinous rice flour"), 362, 8.2, 78.8, 1.6));
        items.add(food("Bột gạo tẻ", "Rice ordinary flour", "Ngũ cốc và sản phẩm chế biến", List.of("bot gao te", "rice ordinary flour"), 359, 6.6, 82.2, 0.4));
        items.add(food("Bột mì", "Wheat flour", "Ngũ cốc và sản phẩm chế biến", List.of("bot mi", "wheat flour"), 346, 10.3, 73.6, 1.1));
        items.add(food("Bột ngô vàng", "Yellow maize flour", "Ngũ cốc và sản phẩm chế biến", List.of("bot ngo vang", "yellow maize flour"), 361, 8.3, 73.0, 4.0));
        items.add(food("Bún", "Rice vermicelli", "Ngũ cốc và sản phẩm chế biến", List.of("bun", "rice vermicelli"), 110, 1.7, 25.7, 0.0));
        items.add(food("Cốm", "Rice, unriped. Raw", "Ngũ cốc và sản phẩm chế biến", List.of("com", "rice, unriped. raw"), 297, 6.1, 66.3, 0.8));
        items.add(food("Mỳ sợi", "Wheat noodles", "Ngũ cốc và sản phẩm chế biến", List.of("my soi", "wheat noodles"), 349, 11.0, 74.2, 0.9));
        items.add(food("Ngô nếp luộc", "Glutinous maize, boiled", "Ngũ cốc và sản phẩm chế biến", List.of("ngo nep luoc", "glutinous maize, boiled"), 167, 3.9, 32.9, 2.2));
        items.add(food("Củ ấu", "Water-caltrops", "Khoai củ và sản phẩm chế biến", List.of("cu au", "water-caltrops"), 115, 3.6, 24.0, 0.5));
        items.add(food("Củ cái", "Yam winged", "Khoai củ và sản phẩm chế biến", List.of("cu cai", "yam winged"), 127, 3.1, 28.3, 0.2));
        items.add(food("Củ dong", "Bermuda tuber", "Khoai củ và sản phẩm chế biến", List.of("cu dong", "bermuda tuber"), 119, 1.4, 28.4, 0.0));
        items.add(food("Củ sắn", "Bitter cassava", "Khoai củ và sản phẩm chế biến", List.of("cu san", "bitter cassava"), 152, 1.1, 36.4, 0.2));
        items.add(food("Củ sắn dây", "Radix puerariae", "Khoai củ và sản phẩm chế biến", List.of("cu san day", "radix puerariae"), 119, 1.6, 28.0, 0.1));
        items.add(food("Củ súng khô (đã bỏ vỏ)", "Nymphaea stellata wild, dried, unshelled", "Khoai củ và sản phẩm chế biến", List.of("cu sung kho (đa bo vo)", "nymphaea stellata wild, dried, unshelled"), 350, 16.1, 70.3, 0.5));
        items.add(food("Củ từ", "Igname Yam, Chinese", "Khoai củ và sản phẩm chế biến", List.of("cu tu", "igname yam, chinese"), 92, 1.5, 21.5, 0.0));
        items.add(food("Khoai lang", "Sweet potato, white", "Khoai củ và sản phẩm chế biến", List.of("khoai lang", "sweet potato, white"), 119, 0.8, 28.5, 0.2));
        items.add(food("Khoai lang nghệ", "Sweet potato, yellow", "Khoai củ và sản phẩm chế biến", List.of("khoai lang nghe", "sweet potato, yellow"), 116, 1.2, 27.1, 0.3));
        items.add(food("Khoai môn", "Chinese Yam, spiny yam", "Khoai củ và sản phẩm chế biến", List.of("khoai mon", "chinese yam, spiny yam"), 109, 1.5, 25.2, 0.2));
        items.add(food("Khoai nước", "Water-taro", "Khoai củ và sản phẩm chế biến", List.of("khoai nuoc", "water-taro"), 98, 1.0, 23.3, 0.1));
        items.add(food("Khoai riềng", "Edible canna", "Khoai củ và sản phẩm chế biến", List.of("khoai rieng", "edible canna"), 104, 0.8, 25.1, 0.0));
        items.add(food("Khoai sọ", "Taro tuber", "Khoai củ và sản phẩm chế biến", List.of("khoai so", "taro tuber"), 114, 1.8, 26.5, 0.1));
        items.add(food("Khoai tây", "Potato, white", "Khoai củ và sản phẩm chế biến", List.of("khoai tay", "potato, white"), 93, 2.0, 20.9, 0.1));
        items.add(food("Miến dong", "Vermicelli from Bermuda tuber", "Khoai củ và sản phẩm chế biến", List.of("mien dong", "vermicelli from bermuda tuber"), 332, 0.6, 82.2, 0.1));
        items.add(food("Bột dong lọc", "Bermuda flour", "Khoai củ và sản phẩm chế biến", List.of("bot dong loc", "bermuda flour"), 341, 0.6, 84.7, 0.0));
        items.add(food("Bột khoai lang", "Sweet potato flour", "Khoai củ và sản phẩm chế biến", List.of("bot khoai lang", "sweet potato flour"), 334, 2.2, 80.2, 0.5));
        items.add(food("Bột khoai riềng (bột đao)", "Canna edulis Ker, flour", "Khoai củ và sản phẩm chế biến", List.of("bot khoai rieng (bot đao)", "canna edulis ker, flour"), 337, 0.2, 84.1, 0.0));
        items.add(food("Bột khoai tây (lọc)", "Potato flour, white", "Khoai củ và sản phẩm chế biến", List.of("bot khoai tay (loc)", "potato flour, white"), 345, 1.0, 84.4, 0.3));
        items.add(food("Bột sắn", "Cassava flour", "Khoai củ và sản phẩm chế biến", List.of("bot san", "cassava flour"), 333, 2.4, 79.6, 0.5));
        items.add(food("Bột sắn dây", "Radix puerariae flour", "Khoai củ và sản phẩm chế biến", List.of("bot san day", "radix puerariae flour"), 340, 0.7, 84.3, 0.0));
        items.add(food("Khoai lang khô", "Sweet potato, dried", "Khoai củ và sản phẩm chế biến", List.of("khoai lang kho", "sweet potato, dried"), 333, 2.2, 80.0, 0.5));
        items.add(food("Khoai tây khô", "Potato, white, dried", "Khoai củ và sản phẩm chế biến", List.of("khoai tay kho", "potato, white, dried"), 330, 6.6, 75.1, 0.3));
        items.add(food("Khoai tây lát chiên", "Potato crisp, fried", "Khoai củ và sản phẩm chế biến", List.of("khoai tay lat chien", "potato crisp, fried"), 525, 2.2, 49.3, 35.4));
        items.add(food("Sắn khô", "Dried bitter cassava", "Khoai củ và sản phẩm chế biến", List.of("san kho", "dried bitter cassava"), 340, 3.0, 80.3, 0.7));
        items.add(food("Trân châu sắn", "Tapioca, pearls E.P", "Khoai củ và sản phẩm chế biến", List.of("tran chau san", "tapioca, pearls e.p"), 341, 1.0, 84.3, 0.0));
        items.add(food("Cùi dừa già", "Coconut meat, mature, raw", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("cui dua gia", "coconut meat, mature, raw"), 368, 4.8, 6.2, 36.0));
        items.add(food("Cùi dừa non", "Coconut meat, immature, raw", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("cui dua non", "coconut meat, immature, raw"), 40, 3.5, 2.6, 1.7));
        items.add(food("Đậu cô ve (hạt)", "French bean seeds, dried", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("đau co ve (hat)", "french bean seeds, dried"), 321, 21.8, 54.9, 1.6));
        items.add(food("Đậu đen (hạt)", "Black bean seeds, dried", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("đau đen (hat)", "black bean seeds, dried"), 325, 24.2, 53.3, 1.7));
        items.add(food("Đậu đũa (hạt)", "Cow pea whole seeds, dried", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("đau đua (hat)", "cow pea whole seeds, dried"), 320, 23.7, 51.9, 2.0));
        items.add(food("Đậu Hà lan (hạt)", "Peas garden and field, seeds, dried", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("đau ha lan (hat)", "peas garden and field, seeds, dried"), 318, 22.2, 54.1, 1.4));
        items.add(food("Đậu tương (đậu nành)", "Yellow dried soybean seeds, dried", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("đau tuong (đau nanh)", "yellow dried soybean seeds, dried"), 400, 34.0, 24.6, 18.4));
        items.add(food("Đậu trắng hạt (Đậu Tây)", "Kidney bean whole seeds, dried", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("đau trang hat (đau tay)", "kidney bean whole seeds, dried"), 327, 23.2, 53.8, 2.1));
        items.add(food("Đậu trứng cuốc", "Egg bird bean seeds, dried", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("đau trung cuoc", "egg bird bean seeds, dried"), 321, 25.8, 50.0, 2.0));
        items.add(food("Đậu xanh (đậu tắt)", "Mungo bean seeds, dried", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("đau xanh (đau tat)", "mungo bean seeds, dried"), 328, 23.4, 53.1, 2.4));
        items.add(food("Hạt dẻ to", "Chestnut, Chinese whole, raw", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("hat de to", "chestnut, chinese whole, raw"), 638, 18.0, 8.7, 59.0));
        items.add(food("Hạt dẻ tươi", "Chestnut, Chinese whole, raw", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("hat de tuoi", "chestnut, chinese whole, raw"), 223, 4.2, 49.1, 1.1));
        items.add(food("Hạt dẻ khô", "Chestnut, dried", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("hat de kho", "chestnut, dried"), 363, 6.8, 79.8, 1.8));
        items.add(food("Hạt đen", "Black seed", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("hat đen", "black seed"), 472, 17.3, 35.5, 29.0));
        items.add(food("Hạt điều", "Cashew nut, common", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("hat đieu", "cashew nut, common"), 605, 18.4, 28.7, 46.3));
        items.add(food("Hạt mít", "Jack fruit, seed, raw", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("hat mit", "jack fruit, seed, raw"), 166, 0.7, 38.3, 1.1));
        items.add(food("Lạc hạt", "Dried peanut seed", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("lac hat", "dried peanut seed"), 573, 27.5, 15.5, 44.5));
        items.add(food("Quả cọ tươi", "Palm fruit fresh", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("qua co tuoi", "palm fruit fresh"), 178, 2.3, 12.1, 13.4));
        items.add(food("Quả đại hái tươi", "Hodgsonia fruit", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("qua đai hai tuoi", "hodgsonia fruit"), 427, 20.0, 1.2, 38.0));
        items.add(food("Vừng (đen, trắng)", "Sesame oriental seeds, whole, dried black or white", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("vung (đen, trang)", "sesame oriental seeds, whole, dried black or white"), 568, 20.1, 17.6, 46.4));
        items.add(food("Bột đậu tương đã loại béo (đậu nành)", "Soybeans flour, defatted", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("bot đau tuong đa loai beo (đau nanh)", "soybeans flour, defatted"), 321, 49.0, 29.0, 1.0));
        items.add(food("Bột đậu tương rang chín", "Roasted soybeans flour", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("bot đau tuong rang chin", "roasted soybeans flour"), 418, 41.0, 22.9, 18.0));
        items.add(food("Bột đậu xanh", "Mungo bean flour", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("bot đau xanh", "mungo bean flour"), 347, 24.6, 56.5, 2.5));
        items.add(food("Bột lạc", "Peanut flour", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("bot lac", "peanut flour"), 575, 27.5, 15.0, 45.0));
        items.add(food("Đậu phụ", "Soybean curt cake pressed, raw", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("đau phu", "soybean curt cake pressed, raw"), 95, 10.9, 0.7, 5.4));
        items.add(food("Đậu phụ chúc", "Curd tofu concentrated", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("đau phu chuc", "curd tofu concentrated"), 414, 50.2, 6.5, 20.8));
        items.add(food("Đậu phụ nướng", "Curd tofu, fried", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("đau phu nuong", "curd tofu, fried"), 114, 13.4, 0.8, 6.4));
        items.add(food("Hạt bí đỏ rang", "Pumpkin seeds, fried", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("hat bi đo rang", "pumpkin seeds, fried"), 519, 35.1, 23.0, 31.8));
        items.add(food("Hạt dưa đỏ rang (dưa hấu)", "Water melon seeds whole, fried", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("hat dua đo rang (dua hau)", "water melon seeds whole, fried"), 551, 31.8, 18.0, 39.1));
        items.add(food("Hạt điều khô, chiên dầu", "Cashew, common, roasted with oil", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("hat đieu kho, chien dau", "cashew, common, roasted with oil"), 583, 18.3, 16.4, 49.3));
        items.add(food("Sữa bột đậu nành", "Milk flour, made from roasted soybeans", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("sua bot đau nanh", "milk flour, made from roasted soybeans"), 405, 31.1, 48.2, 9.7));
        items.add(food("Sữa đậu nành (100g đậu/lít)", "Soybean milk (100 g soybean/l)", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("sua đau nanh (100g đau/lit)", "soybean milk (100 g soybean/l)"), 28, 3.1, 0.4, 1.6));
        items.add(food("Tào phớ", "Tofu in light syrup (Tofu 160g, sirup 65ml)", "Hạt, quả giàu đạm, béo và sản phẩm chế biến", List.of("tao pho", "tofu in light syrup (tofu 160g, sirup 65ml)"), 37, 2.3, 6.4, 0.2));
        items.add(food("Bầu", "Calabash, Bottle gourd", "Rau, quả, củ dùng làm rau", List.of("bau", "calabash, bottle gourd"), 14, 0.6, 2.9, 0.02));
        items.add(food("Bí đao (bí xanh)", "Asgourd Waxgoured, Winter melon", "Rau, quả, củ dùng làm rau", List.of("bi đao (bi xanh)", "asgourd waxgoured, winter melon"), 12, 0.6, 2.4, 0.0));
        items.add(food("Bí ngô", "Pumpkin squash", "Rau, quả, củ dùng làm rau", List.of("bi ngo", "pumpkin squash"), 27, 0.3, 6.1, 0.1));
        items.add(food("Cà bát", "Egg plant big, Brinja aubergine", "Rau, quả, củ dùng làm rau", List.of("ca bat", "egg plant big, brinja aubergine"), 23, 1.2, 4.0, 0.2));
        items.add(food("Cà chua", "Tomato", "Rau, quả, củ dùng làm rau", List.of("ca chua", "tomato"), 20, 0.6, 4.0, 0.2));
        items.add(food("Cà pháo", "Egg plant - small", "Rau, quả, củ dùng làm rau", List.of("ca phao", "egg plant - small"), 20, 1.5, 3.6, 0.0));
        items.add(food("Cà rốt (củ đỏ, vàng)", "Carrots", "Rau, quả, củ dùng làm rau", List.of("ca rot (cu đo, vang)", "carrots"), 39, 1.5, 7.8, 0.2));
        items.add(food("Cà rốt khô", "Dried carrot", "Rau, quả, củ dùng làm rau", List.of("ca rot kho", "dried carrot"), 292, 9.2, 60.4, 1.5));
        items.add(food("Cà tím", "Aubergine", "Rau, quả, củ dùng làm rau", List.of("ca tim", "aubergine"), 22, 1.0, 4.5, 0.0));
        items.add(food("Cải bắp", "Cabbage, common", "Rau, quả, củ dùng làm rau", List.of("cai bap", "cabbage, common"), 29, 1.8, 5.3, 0.1));
        items.add(food("Cải bắp đỏ", "Cabbage, red", "Rau, quả, củ dùng làm rau", List.of("cai bap đo", "cabbage, red"), 45, 1.9, 9.0, 0.2));
        items.add(food("Cải bắp khô", "Dried cabbage, white", "Rau, quả, củ dùng làm rau", List.of("cai bap kho", "dried cabbage, white"), 245, 18.0, 39.7, 1.6));
        items.add(food("Cải cúc", "Chrysanthemum. crown-daisy", "Rau, quả, củ dùng làm rau", List.of("cai cuc", "chrysanthemum. crown-daisy"), 14, 1.6, 1.9, 0.0));
        items.add(food("Cải soong", "Watercress", "Rau, quả, củ dùng làm rau", List.of("cai soong", "watercress"), 15, 2.1, 1.3, 0.1));
        items.add(food("Cải thìa (cải trắng)", "Chinese cabbage, white", "Rau, quả, củ dùng làm rau", List.of("cai thia (cai trang)", "chinese cabbage, white"), 17, 1.4, 2.4, 0.2));
        items.add(food("Cải xanh", "Mustard greens, India, leaves and stems", "Rau, quả, củ dùng làm rau", List.of("cai xanh", "mustard greens, india, leaves and stems"), 16, 1.7, 1.9, 0.2));
        items.add(food("Cần ta", "Water drop-wort; Celery water", "Rau, quả, củ dùng làm rau", List.of("can ta", "water drop-wort; celery water"), 10, 1.0, 1.5, 0.0));
        items.add(food("Cần tây", "Celery, Chinese", "Rau, quả, củ dùng làm rau", List.of("can tay", "celery, chinese"), 48, 3.7, 7.9, 0.2));
        items.add(food("Chuối xanh", "Banana common varieties, unripe", "Rau, quả, củ dùng làm rau", List.of("chuoi xanh", "banana common varieties, unripe"), 74, 1.2, 16.4, 0.5));
        items.add(food("Củ cải đỏ", "Red radish oriental, raw", "Rau, quả, củ dùng làm rau", List.of("cu cai đo", "red radish oriental, raw"), 48, 1.3, 10.8, 0.0));
        items.add(food("Củ cải trắng", "Radish garden while, raw", "Rau, quả, củ dùng làm rau", List.of("cu cai trang", "radish garden while, raw"), 21, 1.5, 3.6, 0.1));
        items.add(food("Củ cải trắng khô", "Dried radish, white", "Rau, quả, củ dùng làm rau", List.of("cu cai trang kho", "dried radish, white"), 220, 17.6, 33.9, 1.5));
        items.add(food("Củ đậu", "Pachyrrhizus", "Rau, quả, củ dùng làm rau", List.of("cu đau", "pachyrrhizus"), 28, 1.0, 6.0, 0.0));
        items.add(food("Củ niễng", "Manchurian water-rice, Manchurian Wild rice", "Rau, quả, củ dùng làm rau", List.of("cu nieng", "manchurian water-rice, manchurian wild rice"), 30, 2.0, 5.4, 0.0));
        items.add(food("Dọc củ cải (non)", "Horse radish; dish - tree, drumstick leave", "Rau, quả, củ dùng làm rau", List.of("doc cu cai (non)", "horse radish; dish - tree, drumstick leave"), 14, 1.9, 1.6, 0.0));
        items.add(food("Dọc mùng", "Colocasia indica", "Rau, quả, củ dùng làm rau", List.of("doc mung", "colocasia indica"), 5, 0.4, 0.8, 0.0));
        items.add(food("Dưa chuột", "Cucumber", "Rau, quả, củ dùng làm rau", List.of("dua chuot", "cucumber"), 16, 0.8, 2.9, 0.1));
        items.add(food("Dưa gang", "Large cucumber", "Rau, quả, củ dùng làm rau", List.of("dua gang", "large cucumber"), 11, 0.8, 2.0, 0.0));
        items.add(food("Đậu cô ve", "Beans, kidney, in pod, French bean; Navy been", "Rau, quả, củ dùng làm rau", List.of("đau co ve", "beans, kidney, in pod, french bean; navy been"), 73, 5.0, 13.3, 0.0));
        items.add(food("Đậu đũa", "Cow-peas, yard long, Chinese long bean", "Rau, quả, củ dùng làm rau", List.of("đau đua", "cow-peas, yard long, chinese long bean"), 59, 6.0, 7.9, 0.4));
        items.add(food("Đậu Hà Lan", "Green peas; field pea; Peas garden", "Rau, quả, củ dùng làm rau", List.of("đau ha lan", "green peas; field pea; peas garden"), 72, 6.5, 10.6, 0.4));
        items.add(food("Đậu rồng (quả non)", "Winged bean goabean, Indies, asparagus pea", "Rau, quả, củ dùng làm rau", List.of("đau rong (qua non)", "winged bean goabean, indies, asparagus pea"), 34, 1.9, 6.3, 0.1));
        items.add(food("Đu đủ xanh", "Papaya, unripe, raw", "Rau, quả, củ dùng làm rau", List.of("đu đu xanh", "papaya, unripe, raw"), 22, 0.8, 4.6, 0.0));
        items.add(food("Gấc", "Gac fruit, whole", "Rau, quả, củ dùng làm rau", List.of("gac", "gac fruit, whole"), 122, 2.1, 10.5, 7.9));
        items.add(food("Giá đậu tương", "Sprout of soybeans", "Rau, quả, củ dùng làm rau", List.of("gia đau tuong", "sprout of soybeans"), 79, 7.7, 8.0, 1.8));
        items.add(food("Giá đậu xanh", "Mungobean sprouts, Green gram, Tiensin green bean", "Rau, quả, củ dùng làm rau", List.of("gia đau xanh", "mungobean sprouts, green gram, tiensin green bean"), 44, 5.5, 5.1, 0.2));
        items.add(food("Hành củ tươi", "Onion, Welsh", "Rau, quả, củ dùng làm rau", List.of("hanh cu tuoi", "onion, welsh"), 26, 1.3, 4.4, 0.4));
        items.add(food("Hành lá (hành hoa)", "Onion, Welsh", "Rau, quả, củ dùng làm rau", List.of("hanh la (hanh hoa)", "onion, welsh"), 22, 1.3, 4.3, 0.0));
        items.add(food("Hành tây", "Onion, common, garden", "Rau, quả, củ dùng làm rau", List.of("hanh tay", "onion, common, garden"), 41, 1.8, 8.2, 0.1));
        items.add(food("Hạt sen tươi", "Lotus seed, raw", "Rau, quả, củ dùng làm rau", List.of("hat sen tuoi", "lotus seed, raw"), 161, 9.5, 29.5, 0.5));
        items.add(food("Hạt sen khô", "Dried lotus seed", "Rau, quả, củ dùng làm rau", List.of("hat sen kho", "dried lotus seed"), 334, 20.0, 58.0, 2.4));
        items.add(food("Hẹ lá", "Onion, fragrant, Chinese leek", "Rau, quả, củ dùng làm rau", List.of("he la", "onion, fragrant, chinese leek"), 18, 2.2, 1.5, 0.3));
        items.add(food("Hoa chuối", "Banana, buds and flowers", "Rau, quả, củ dùng làm rau", List.of("hoa chuoi", "banana, buds and flowers"), 20, 1.5, 3.5, 0.0));
        items.add(food("Hoa lý", "Daylily, lemon flowers, Pergularia, raw", "Rau, quả, củ dùng làm rau", List.of("hoa ly", "daylily, lemon flowers, pergularia, raw"), 23, 2.9, 2.8, 0.0));
        items.add(food("Khế", "Carambola; Star fruit", "Rau, quả, củ dùng làm rau", List.of("khe", "carambola; star fruit"), 16, 0.6, 2.8, 0.3));
        items.add(food("Lá lốt", "Lolot", "Rau, quả, củ dùng làm rau", List.of("la lot", "lolot"), 39, 4.3, 5.4, 0.0));
        items.add(food("Lá me", "Tamarind, leaves", "Rau, quả, củ dùng làm rau", List.of("la me", "tamarind, leaves"), 46, 7.5, 4.0, 0.0));
        items.add(food("Lá mơ lông", "Wild plant", "Rau, quả, củ dùng làm rau", List.of("la mo long", "wild plant"), 27, 3.9, 2.9, 0.0));
        items.add(food("Lá sắn tươi", "Cassava leaves", "Rau, quả, củ dùng làm rau", List.of("la san tuoi", "cassava leaves"), 78, 7.0, 12.6, 0.0));
        items.add(food("Măng chua", "Bamboo shoot, unspecified", "Rau, quả, củ dùng làm rau", List.of("mang chua", "bamboo shoot, unspecified"), 11, 1.4, 1.4, 0.0));
        items.add(food("Măng khô", "Dried bamboo shoots", "Rau, quả, củ dùng làm rau", List.of("mang kho", "dried bamboo shoots"), 157, 13.0, 21.5, 2.1));
        items.add(food("Măng tây", "Asparagus, white", "Rau, quả, củ dùng làm rau", List.of("mang tay", "asparagus, white"), 14, 2.2, 1.1, 0.1));
        items.add(food("Măng tre", "Bamboo shoots, spring variety", "Rau, quả, củ dùng làm rau", List.of("mang tre", "bamboo shoots, spring variety"), 15, 1.7, 1.4, 0.3));
        items.add(food("Mướp", "Gourd, sponge gourd", "Rau, quả, củ dùng làm rau", List.of("muop", "gourd, sponge gourd"), 17, 0.9, 2.8, 0.2));
        items.add(food("Mướp đắng", "Balsam-pear, balsam-apple, bitter melon, bitter gourd", "Rau, quả, củ dùng làm rau", List.of("muop đang", "balsam-pear, balsam-apple, bitter melon, bitter gourd"), 16, 0.9, 2.8, 0.2));
        items.add(food("Mướp Nhật bản", "Gourd, sponge gourd, Japanese", "Rau, quả, củ dùng làm rau", List.of("muop nhat ban", "gourd, sponge gourd, japanese"), 10, 0.8, 1.8, 0.0));
        items.add(food("Ngải cứu", "Mugwort, common sagebrush", "Rau, quả, củ dùng làm rau", List.of("ngai cuu", "mugwort, common sagebrush"), 25, 3.8, 2.4, 0.0));
        items.add(food("Ngô bao tử", "Corn, small variety immature, baby corn", "Rau, quả, củ dùng làm rau", List.of("ngo bao tu", "corn, small variety immature, baby corn"), 40, 2.2, 7.4, 0.2));
        items.add(food("Ngó sen", "Lotus, stem underground", "Rau, quả, củ dùng làm rau", List.of("ngo sen", "lotus, stem underground"), 61, 1.0, 13.9, 0.1));
        items.add(food("Nụ mướp", "Sponge gourd, rag, young flower", "Rau, quả, củ dùng làm rau", List.of("nu muop", "sponge gourd, rag, young flower"), 30, 4.9, 2.5, 0.0));
        items.add(food("ớt đỏ to", "Chili pepper, peppers red", "Rau, quả, củ dùng làm rau", List.of("ot đo to", "chili pepper, peppers red"), 23, 1.0, 4.0, 0.3));
        items.add(food("ớt vàng to", "Peppers, yellow", "Rau, quả, củ dùng làm rau", List.of("ot vang to", "peppers, yellow"), 29, 1.3, 5.5, 0.2));
        items.add(food("ớt xanh to", "Peppers, green", "Rau, quả, củ dùng làm rau", List.of("ot xanh to", "peppers, green"), 25, 1.3, 4.5, 0.2));
        items.add(food("Quả dọc", null, "Rau, quả, củ dùng làm rau", List.of("qua doc"), 19, 0.8, 3.9, 0.0));
        items.add(food("Quả me chua", "Tamarind fruit, pulp raw", "Rau, quả, củ dùng làm rau", List.of("qua me chua", "tamarind fruit, pulp raw"), 27, 1.9, 4.8, 0.0));
        items.add(food("Rau bí", "Pumpkin leaves", "Rau, quả, củ dùng làm rau", List.of("rau bi", "pumpkin leaves"), 18, 2.7, 1.7, 0.0));
        items.add(food("Rau câu khô", "Dried seaweed", "Rau, quả, củ dùng làm rau", List.of("rau cau kho", "dried seaweed"), 198, 11.2, 35.8, 1.1));
        items.add(food("Rau câu tươi", "Seaweed fresh", "Rau, quả, củ dùng làm rau", List.of("rau cau tuoi", "seaweed fresh"), 25, 1.9, 4.1, 0.1));
        items.add(food("Rau diếp", "Lettuce garden", "Rau, quả, củ dùng làm rau", List.of("rau diep", "lettuce garden"), 14, 1.2, 1.8, 0.2));
        items.add(food("Rau đay", "Jute potherb", "Rau, quả, củ dùng làm rau", List.of("rau đay", "jute potherb"), 25, 2.8, 3.0, 0.3));
        items.add(food("Rau giấp cá, diếp cá", "Wild plant", "Rau, quả, củ dùng làm rau", List.of("rau giap ca, diep ca", "wild plant"), 22, 2.9, 2.7, 0.0));
        items.add(food("Rau giền cơm", "Amaranth, spineless", "Rau, quả, củ dùng làm rau", List.of("rau gien com", "amaranth, spineless"), 21, 3.4, 1.1, 0.3));
        items.add(food("Rau giền đỏ", "Amaranth, sp. Red", "Rau, quả, củ dùng làm rau", List.of("rau gien đo", "amaranth, sp. red"), 41, 3.3, 6.2, 0.3));
        items.add(food("Rau giền trắng", "Amaranth, sp White", "Rau, quả, củ dùng làm rau", List.of("rau gien trang", "amaranth, sp white"), 42, 3.2, 6.3, 0.4));
        items.add(food("Rau húng", "Basil sweet leaves, raw", "Rau, quả, củ dùng làm rau", List.of("rau hung", "basil sweet leaves, raw"), 20, 2.2, 1.5, 0.6));
        items.add(food("Rau khoai lang", "Sweet potato, leaves", "Rau, quả, củ dùng làm rau", List.of("rau khoai lang", "sweet potato, leaves"), 23, 2.6, 2.5, 0.3));
        items.add(food("Rau kinh giới", "Sweet marjoram", "Rau, quả, củ dùng làm rau", List.of("rau kinh gioi", "sweet marjoram"), 22, 2.7, 2.8, 0.0));
        items.add(food("Rau má rừng", "Wild plant", "Rau, quả, củ dùng làm rau", List.of("rau ma rung", "wild plant"), 25, 3.1, 3.1, 0.0));
        items.add(food("Rau má, má mơ", "Wort, India penny", "Rau, quả, củ dùng làm rau", List.of("rau ma, ma mo", "wort, india penny"), 20, 3.2, 1.8, 0.0));
        items.add(food("Rau mồng tơi", "Malabar night shade, Vinespinach, Ceylon spinach", "Rau, quả, củ dùng làm rau", List.of("rau mong toi", "malabar night shade, vinespinach, ceylon spinach"), 14, 2.0, 1.4, 0.0));
        items.add(food("Rau mùi", "Coriander", "Rau, quả, củ dùng làm rau", List.of("rau mui", "coriander"), 16, 2.6, 0.2, 0.5));
        items.add(food("Rau mùi tàu", "Parsley, curley", "Rau, quả, củ dùng làm rau", List.of("rau mui tau", "parsley, curley"), 25, 2.1, 2.4, 0.8));
        items.add(food("Rau muống", "Swamp cabbage, water spinach, water convol", "Rau, quả, củ dùng làm rau", List.of("rau muong", "swamp cabbage, water spinach, water convol"), 25, 3.2, 2.1, 0.4));
        items.add(food("Rau muống khô", "Water spinach, dried", "Rau, quả, củ dùng làm rau", List.of("rau muong kho", "water spinach, dried"), 245, 34.2, 23.0, 1.8));
        items.add(food("Rau ngổ", "Limnophila aromatic", "Rau, quả, củ dùng làm rau", List.of("rau ngo", "limnophila aromatic"), 15, 1.5, 2.3, 0.0));
        items.add(food("Rau ngót", "Sauropus, sp. leaves", "Rau, quả, củ dùng làm rau", List.of("rau ngot", "sauropus, sp. leaves"), 35, 5.3, 3.4, 0.0));
        items.add(food("Rau ngót khô", "Sauropus, dried", "Rau, quả, củ dùng làm rau", List.of("rau ngot kho", "sauropus, dried"), 239, 32.2, 21.8, 2.6));
        items.add(food("Rau răm", "Polygonum odoratum", "Rau, quả, củ dùng làm rau", List.of("rau ram", "polygonum odoratum"), 30, 4.7, 2.8, 0.0));
        items.add(food("Rau rút", "Neptunia, dismanthus", "Rau, quả, củ dùng làm rau", List.of("rau rut", "neptunia, dismanthus"), 28, 5.1, 1.8, 0.0));
        items.add(food("Rau sà lách", "Lettuce, garden asparagus", "Rau, quả, củ dùng làm rau", List.of("rau sa lach", "lettuce, garden asparagus"), 17, 1.5, 1.8, 0.4));
        items.add(food("Rau sam", "Purslane, common", "Rau, quả, củ dùng làm rau", List.of("rau sam", "purslane, common"), 18, 1.4, 3.0, 0.0));
        items.add(food("Rau sắng (chùa Hương)", "Perfume pagoda wild plant", "Rau, quả, củ dùng làm rau", List.of("rau sang (chua huong)", "perfume pagoda wild plant"), 48, 6.5, 5.5, 0.0));
        items.add(food("Rau tàu bay", "Gynura crepidioides", "Rau, quả, củ dùng làm rau", List.of("rau tau bay", "gynura crepidioides"), 18, 2.5, 1.9, 0.0));
        items.add(food("Rau thơm", "Mint leaves", "Rau, quả, củ dùng làm rau", List.of("rau thom", "mint leaves"), 18, 2.0, 2.4, 0.0));
        items.add(food("Sấu xanh", "Dracontomelum fruit, unripe, raw", "Rau, quả, củ dùng làm rau", List.of("sau xanh", "dracontomelum fruit, unripe, raw"), 19, 1.8, 3.0, 0.0));
        items.add(food("Su hào", "Kohlrabi", "Rau, quả, củ dùng làm rau", List.of("su hao", "kohlrabi"), 37, 2.8, 6.2, 0.1));
        items.add(food("Su hào khô", "Dried kohlrabi", "Rau, quả, củ dùng làm rau", List.of("su hao kho", "dried kohlrabi"), 261, 20.0, 42.1, 1.4));
        items.add(food("Su su, quả", "Chayote, fruit raw", "Rau, quả, củ dùng làm rau", List.of("su su, qua", "chayote, fruit raw"), 19, 0.8, 3.6, 0.1));
        items.add(food("Súp lơ trắng", "Cauliflower, white", "Rau, quả, củ dùng làm rau", List.of("sup lo trang", "cauliflower, white"), 30, 2.5, 4.8, 0.1));
        items.add(food("Súp lơ xanh", "Cauliflower, green", "Rau, quả, củ dùng làm rau", List.of("sup lo xanh", "cauliflower, green"), 26, 3.0, 2.9, 0.3));
        items.add(food("Thìa là", "Dill", "Rau, quả, củ dùng làm rau", List.of("thia la", "dill"), 28, 2.6, 1.8, 1.1));
        items.add(food("Tía tô", "Balm-mint, garden- balm", "Rau, quả, củ dùng làm rau", List.of("tia to", "balm-mint, garden- balm"), 25, 2.9, 3.4, 0.0));
        items.add(food("Tỏi ta", "Garlic bulbs", "Rau, quả, củ dùng làm rau", List.of("toi ta", "garlic bulbs"), 121, 6.0, 23.0, 0.5));
        items.add(food("Tỏi tây (cả lá)", "Chinese Leek, Onion fragrant", "Rau, quả, củ dùng làm rau", List.of("toi tay (ca la)", "chinese leek, onion fragrant"), 29, 1.4, 5.9, 0.0));
        items.add(food("Trám đen chín", "Variety of canarium", "Rau, quả, củ dùng làm rau", List.of("tram đen chin", "variety of canarium"), 114, 2.5, 3.6, 10.0));
        items.add(food("Trám xanh sống, trám trắng", "Chinese olive", "Rau, quả, củ dùng làm rau", List.of("tram xanh song, tram trang", "chinese olive"), 37, 1.2, 4.4, 1.6));
        items.add(food("Xương sông", "Edible herbaceous plant", "Rau, quả, củ dùng làm rau", List.of("xuong song", "edible herbaceous plant"), 15, 2.2, 1.5, 0.0));
        items.add(food("Cà chua muối", "Tomato, pickled", "Rau, quả, củ dùng làm rau", List.of("ca chua muoi", "tomato, pickled"), 6, 0.6, 1.0, 0.0));
        items.add(food("Cà muối nén", "Eggplant, garden, brinjan; aubergine, pickled", "Rau, quả, củ dùng làm rau", List.of("ca muoi nen", "eggplant, garden, brinjan; aubergine, pickled"), 13, 1.3, 2.0, 0.0));
        items.add(food("Cà muối sổi", "Eggplant, garden, brinjan; aubergine, pickled", "Rau, quả, củ dùng làm rau", List.of("ca muoi soi", "eggplant, garden, brinjan; aubergine, pickled"), 16, 1.5, 2.5, 0.0));
        items.add(food("Dưa cải bắp", "Cabbage Chinese, pickled", "Rau, quả, củ dùng làm rau", List.of("dua cai bap", "cabbage chinese, pickled"), 18, 1.2, 3.3, 0.0));
        items.add(food("Dưa cải bẹ", "Mustard green, pickled", "Rau, quả, củ dùng làm rau", List.of("dua cai be", "mustard green, pickled"), 17, 1.8, 2.4, 0.0));
        items.add(food("Dưa cải sen", "Rape bird, pickled", "Rau, quả, củ dùng làm rau", List.of("dua cai sen", "rape bird, pickled"), 10, 1.1, 1.3, 0.0));
        items.add(food("Dưa chuột muối", "Cucumber, pickled", "Rau, quả, củ dùng làm rau", List.of("dua chuot muoi", "cucumber, pickled"), 13, 0.8, 2.5, 0.0));
        items.add(food("Dưa giá (đậu xanh)", "Mung bean sprouts, pickled", "Rau, quả, củ dùng làm rau", List.of("dua gia (đau xanh)", "mung bean sprouts, pickled"), 39, 5.0, 4.8, 0.0));
        items.add(food("Hành củ muối", "Onion, pickled", "Rau, quả, củ dùng làm rau", List.of("hanh cu muoi", "onion, pickled"), 22, 1.4, 4.0, 0.0));
        items.add(food("Kiệu muối", "Onion shallot, scallion, pickled", "Rau, quả, củ dùng làm rau", List.of("kieu muoi", "onion shallot, scallion, pickled"), 24, 1.3, 4.7, 0.0));
        items.add(food("Nhút (muối từ mít non, ngọn đậu xanh non...)", "Mix pickled from young jack fruit", "Rau, quả, củ dùng làm rau", List.of("nhut (muoi tu mit non, ngon đau xanh non...)", "mix pickled from young jack fruit"), 16, 2.5, 1.5, 0.0));
        items.add(food("Men bia khô", "Brewer's yeast, fried", "Rau, quả, củ dùng làm rau", List.of("men bia kho", "brewer's yeast, fried"), 340, 52.5, 25.4, 3.2));
        items.add(food("Men bia tươi", "Baker's yeast, fresh", "Rau, quả, củ dùng làm rau", List.of("men bia tuoi", "baker's yeast, fresh"), 95, 16.2, 4.5, 1.3));
        items.add(food("Mộc nhĩ", "Jew's ear, Juda's ear, dried, Wood-ear, Tender variety", "Rau, quả, củ dùng làm rau", List.of("moc nhi", "jew's ear, juda's ear, dried, wood-ear, tender variety"), 304, 10.6, 65.0, 0.2));
        items.add(food("Nấm hương khô", "Mushroom Chinese, dried", "Rau, quả, củ dùng làm rau", List.of("nam huong kho", "mushroom chinese, dried"), 274, 36.0, 23.5, 4.0));
        items.add(food("Nấm hương tươi", "Mushroom, Chinese, raw", "Rau, quả, củ dùng làm rau", List.of("nam huong tuoi", "mushroom, chinese, raw"), 39, 5.5, 3.1, 0.5));
        items.add(food("Nấm mỡ (Nấm tây)", "Mushroom", "Rau, quả, củ dùng làm rau", List.of("nam mo (nam tay)", "mushroom"), 32, 4.0, 3.4, 0.3));
        items.add(food("Nấm rơm", "Mushroom, straw", "Rau, quả, củ dùng làm rau", List.of("nam rom", "mushroom, straw"), 57, 3.6, 3.4, 3.2));
        items.add(food("Nấm thường tươi", "Mushroom, common", "Rau, quả, củ dùng làm rau", List.of("nam thuong tuoi", "mushroom, common"), 34, 4.6, 2.2, 0.8));
        items.add(food("Bưởi", "Pomelo, Pummelo; Shaddock", "Quả chín", List.of("buoi", "pomelo, pummelo; shaddock"), 30, 0.2, 7.3, 0.0));
        items.add(food("Cam", "Orange", "Quả chín", List.of("cam", "orange"), 38, 0.9, 8.3, 0.1));
        items.add(food("Chanh", "Lemon", "Quả chín", List.of("chanh", "lemon"), 24, 0.9, 4.5, 0.3));
        items.add(food("Chôm chôm", "Rambutan", "Quả chín", List.of("chom chom", "rambutan"), 72, 1.5, 16.4, 0.0));
        items.add(food("Chuối khô", "Banana, dried", "Quả chín", List.of("chuoi kho", "banana, dried"), 292, 5.0, 68.0, 0.0));
        items.add(food("Chuối tây", "Banana", "Quả chín", List.of("chuoi tay", "banana"), 56, 0.9, 12.4, 0.3));
        items.add(food("Chuối tiêu", "Banana, dwarf", "Quả chín", List.of("chuoi tieu", "banana, dwarf"), 97, 1.5, 22.2, 0.2));
        items.add(food("Dâu gia", "Blackberry", "Quả chín", List.of("dau gia", "blackberry"), 27, 0.6, 6.2, 0.0));
        items.add(food("Dâu tây", "Strawberry", "Quả chín", List.of("dau tay", "strawberry"), 43, 1.8, 8.1, 0.4));
        items.add(food("Dưa bở", "Musk melon, Spanish melon, Cantaloupe", "Quả chín", List.of("dua bo", "musk melon, spanish melon, cantaloupe"), 18, 0.5, 3.6, 0.2));
        items.add(food("Dưa hấu", "Watermelon", "Quả chín", List.of("dua hau", "watermelon"), 16, 1.2, 2.3, 0.2));
        items.add(food("Dưa hồng", "Honey dew melon", "Quả chín", List.of("dua hong", "honey dew melon"), 17, 0.3, 3.7, 0.1));
        items.add(food("Dưa lê", null, "Quả chín", List.of("dua le"), 18, 0.4, 4.2, 0.0));
        items.add(food("Dứa ta", "Pineapple, wild", "Quả chín", List.of("dua ta", "pineapple, wild"), 29, 0.8, 6.5, 0.0));
        items.add(food("Dứa tây", "Pineapple", "Quả chín", List.of("dua tay", "pineapple"), 38, 0.5, 8.8, 0.1));
        items.add(food("Đào", "Peach", "Quả chín", List.of("đao", "peach"), 31, 0.9, 6.3, 0.2));
        items.add(food("Đu đủ chín", "Papaya, ripe", "Quả chín", List.of("đu đu chin", "papaya, ripe"), 36, 1.0, 7.6, 0.1));
        items.add(food("Gioi", "Ohia; Malaya roseapple", "Quả chín", List.of("gioi", "ohia; malaya roseapple"), 16, 0.4, 3.2, 0.3));
        items.add(food("Hồng bì", "Wampee, Chinese; Wampi", "Quả chín", List.of("hong bi", "wampee, chinese; wampi"), 34, 1.4, 7.2, 0.0));
        items.add(food("Hồng đỏ", "Persimmon kaki, soft type, ripe", "Quả chín", List.of("hong đo", "persimmon kaki, soft type, ripe"), 29, 0.7, 6.0, 0.2));
        items.add(food("Hồng ngâm", "Persimmon kaki, Hard-type, ripe", "Quả chín", List.of("hong ngam", "persimmon kaki, hard-type, ripe"), 38, 0.9, 8.6, 0.0));
        items.add(food("Hồng xiêm", "Sapodilla, sapota ponderosa", "Quả chín", List.of("hong xiem", "sapodilla, sapota ponderosa"), 48, 0.5, 10.0, 0.7));
        items.add(food("Lê", "Pear", "Quả chín", List.of("le", "pear"), 45, 0.7, 10.2, 0.2));
        items.add(food("Lựu", "Pome granate", "Quả chín", List.of("luu", "pome granate"), 70, 0.6, 16.2, 0.3));
        items.add(food("Mãng cầu xiêm", "Siamese custard apple, soursop", "Quả chín", List.of("mang cau xiem", "siamese custard apple, soursop"), 53, 1.8, 10.1, 0.6));
        items.add(food("Mắc coọc", "Pyrus pashia Ham", "Quả chín", List.of("mac cooc", "pyrus pashia ham"), 24, 0.2, 5.7, 0.0));
        items.add(food("Mận", "Japanese, plum", "Quả chín", List.of("man", "japanese, plum"), 20, 0.6, 3.9, 0.2));
        items.add(food("Mít dai", "Jackfruit, jackfruit mature", "Quả chín", List.of("mit dai", "jackfruit, jackfruit mature"), 50, 0.6, 11.1, 0.3));
        items.add(food("Mít khô", "Dried jackfruit", "Quả chín", List.of("mit kho", "dried jackfruit"), 280, 2.9, 67.0, 0.0));
        items.add(food("Mít mật", "Jack fruit, honey", "Quả chín", List.of("mit mat", "jack fruit, honey"), 62, 1.5, 14.0, 0.0));
        items.add(food("Mơ", "Apricot, Apricot nectar", "Quả chín", List.of("mo", "apricot, apricot nectar"), 48, 0.9, 10.1, 0.4));
        items.add(food("Mơ khô", "Apricot dried, unsulfured", "Quả chín", List.of("mo kho", "apricot dried, unsulfured"), 273, 3.0, 62.8, 1.1));
        items.add(food("Muỗm, quéo", "Mango, common; Indian mango, unripe", "Quả chín", List.of("muom, queo", "mango, common; indian mango, unripe"), 67, 0.6, 15.3, 0.4));
        items.add(food("Na", "Sugarapple, sweetsop", "Quả chín", List.of("na", "sugarapple, sweetsop"), 66, 1.6, 14.2, 0.3));
        items.add(food("Nhãn", "Longan", "Quả chín", List.of("nhan", "longan"), 48, 0.9, 10.9, 0.1));
        items.add(food("Nhãn khô", "Longan, dried", "Quả chín", List.of("nhan kho", "longan, dried"), 285, 4.3, 65.9, 0.5));
        items.add(food("Nho ngọt", "Grape, European, sweet", "Quả chín", List.of("nho ngot", "grape, european, sweet"), 68, 0.4, 16.3, 0.2));
        items.add(food("Nho ta (nho chua)", "Grape fruit, sour", "Quả chín", List.of("nho ta (nho chua)", "grape fruit, sour"), 14, 0.4, 3.1, 0.0));
        items.add(food("Nhót", "Silver berry", "Quả chín", List.of("nhot", "silver berry"), 13, 1.2, 2.1, 0.0));
        items.add(food("ổi", "Guava, common", "Quả chín", List.of("oi", "guava, common"), 38, 0.6, 6.8, 1.0));
        items.add(food("Quả bơ vỏ tím", "Avocado, purple", "Quả chín", List.of("qua bo vo tim", "avocado, purple"), 74, 1.8, 2.8, 6.2));
        items.add(food("Quả bơ vỏ xanh", "Avocado, green", "Quả chín", List.of("qua bo vo xanh", "avocado, green"), 101, 1.9, 2.3, 9.4));
        items.add(food("Quả cóc", null, "Quả chín", List.of("qua coc"), 58, 1.8, 12.8, 0.0));
        items.add(food("Quả thanh long", "Dragon's eyes fruit", "Quả chín", List.of("qua thanh long", "dragon's eyes fruit"), 40, 1.3, 8.7, 0.0));
        items.add(food("Quả trứng gà", null, "Quả chín", List.of("qua trung ga"), 106, 4.3, 21.3, 0.4));
        items.add(food("Quất chín (cả vỏ)", "Mandarin, whole fruit", "Quả chín", List.of("quat chin (ca vo)", "mandarin, whole fruit"), 26, 0.9, 5.5, 0.0));
        items.add(food("Quít", "Tangerine; Orange; Mandarin", "Quả chín", List.of("quit", "tangerine; orange; mandarin"), 39, 0.8, 8.3, 0.3));
        items.add(food("Sầu riêng", "Durian, Civet", "Quả chín", List.of("sau rieng", "durian, civet"), 132, 2.5, 26.9, 1.6));
        items.add(food("Sấu chín", "Sanpidus, ripe", "Quả chín", List.of("sau chin", "sanpidus, ripe"), 38, 1.3, 8.2, 0.0));
        items.add(food("Táo ta", "Jujube, common or Chinese; Chinese date", "Quả chín", List.of("tao ta", "jujube, common or chinese; chinese date"), 38, 0.8, 8.3, 0.2));
        items.add(food("Táo tây", "Apple, common, domestic", "Quả chín", List.of("tao tay", "apple, common, domestic"), 48, 0.5, 11.0, 0.2));
        items.add(food("Vải", "Litchi; lychee", "Quả chín", List.of("vai", "litchi; lychee"), 45, 0.7, 9.6, 0.4));
        items.add(food("Vải khô", "Litchi, dried with shells", "Quả chín", List.of("vai kho", "litchi, dried with shells"), 260, 3.0, 57.6, 1.9));
        items.add(food("Vú sữa", "Starapple, cainito", "Quả chín", List.of("vu sua", "starapple, cainito"), 42, 1.0, 9.4, 0.0));
        items.add(food("Xoài chín", "Mango, common; India mango, ripe", "Quả chín", List.of("xoai chin", "mango, common; india mango, ripe"), 62, 0.6, 14.1, 0.3));
        items.add(food("Quả kiwi", "Kiwi fruit", "Quả chín", List.of("qua kiwi", "kiwi fruit"), 56, 1.1, 11.7, 0.5));
        items.add(food("Bơ", "Butter, unsalted", "Dầu, mỡ, bơ", List.of("bo", "butter, unsalted"), 756, 0.5, 0.5, 83.5));
        items.add(food("Dầu thảo mộc (Lạc, vừng, cám...)", "Vegetable oil, mix", "Dầu, mỡ, bơ", List.of("dau thao moc (lac, vung, cam...)", "vegetable oil, mix"), 897, 0.0, 0.0, 99.7));
        items.add(food("Mỡ lợn muối", "Lard, salted", "Dầu, mỡ, bơ", List.of("mo lon muoi", "lard, salted"), 827, 2.0, 0.0, 91.0));
        items.add(food("Mỡ lợn nước", "Lard, liquid", "Dầu, mỡ, bơ", List.of("mo lon nuoc", "lard, liquid"), 896, 0.0, 0.0, 99.6));
        items.add(food("Bơ thực vật", "Butter-margarine blend, stick, unsalted", "Dầu, mỡ, bơ", List.of("bo thuc vat", "butter-margarine blend, stick, unsalted"), 729, 0.5, 0.1, 80.7));
        items.add(food("Dầu bông", "Cottonseed oil, salad or cooking", "Dầu, mỡ, bơ", List.of("dau bong", "cottonseed oil, salad or cooking"), 900, 0.0, 0.0, 100.0));
        items.add(food("Dầu cám gạo", "Rice bran oil", "Dầu, mỡ, bơ", List.of("dau cam gao", "rice bran oil"), 900, 0.0, 0.0, 100.0));
        items.add(food("Dầu cọ", "Palm oil", "Dầu, mỡ, bơ", List.of("dau co", "palm oil"), 900, 0.0, 0.0, 100.0));
        items.add(food("Dầu dừa", "Coconut oil", "Dầu, mỡ, bơ", List.of("dau dua", "coconut oil"), 900, 0.0, 0.0, 100.0));
        items.add(food("Dầu đậu tương", "Soybean oil, salad or cooking", "Dầu, mỡ, bơ", List.of("dau đau tuong", "soybean oil, salad or cooking"), 900, 0.0, 0.0, 100.0));
        items.add(food("Dầu lạc", "Peanut oil, salad or cooking", "Dầu, mỡ, bơ", List.of("dau lac", "peanut oil, salad or cooking"), 900, 0.0, 0.0, 100.0));
        items.add(food("Dầu mè", "Sesame oil, salad or cooking", "Dầu, mỡ, bơ", List.of("dau me", "sesame oil, salad or cooking"), 900, 0.0, 0.0, 100.0));
        items.add(food("Dầu ngô", "Corn oil, salad or cooking", "Dầu, mỡ, bơ", List.of("dau ngo", "corn oil, salad or cooking"), 900, 0.0, 0.0, 100.0));
        items.add(food("Dầu oliu", "Olive oil, salad or cooking", "Dầu, mỡ, bơ", List.of("dau oliu", "olive oil, salad or cooking"), 900, 0.0, 0.0, 100.0));
        items.add(food("Thịt bê mỡ", "Veal meat, lean and fat", "Thịt và sản phẩm chế biến", List.of("thit be mo", "veal meat, lean and fat"), 144, 19.0, 0.0, 7.5));
        items.add(food("Thịt bê nạc", "Veal meat, lean only", "Thịt và sản phẩm chế biến", List.of("thit be nac", "veal meat, lean only"), 85, 20.0, 0.0, 0.5));
        items.add(food("Thịt bò loại I", "Beef, grade I", "Thịt và sản phẩm chế biến", List.of("thit bo loai i", "beef, grade i"), 118, 21.0, 0.0, 3.8));
        items.add(food("Thịt bò loại II", "Beef, grade II", "Thịt và sản phẩm chế biến", List.of("thit bo loai ii", "beef, grade ii"), 167, 18.0, 0.0, 10.5));
        items.add(food("Thịt bò, lưng, nạc", "Beef, top loin, seperable lean only, trimmed to 1/8\" fat, prime, raw", "Thịt và sản phẩm chế biến", List.of("thit bo, lung, nac", "beef, top loin, seperable lean only, trimmed to 1/8\" fat, prime, raw"), 127, 23.1, 0.0, 3.9));
        items.add(food("Thịt bò, lưng, nạc và mỡ", "Beef, top loin, seperable lean only, trimmed to 1/4\" fat, prime, raw", "Thịt và sản phẩm chế biến", List.of("thit bo, lung, nac va mo", "beef, top loin, seperable lean only, trimmed to 1/4\" fat, prime, raw"), 182, 21.5, 0.0, 10.7));
        items.add(food("Thịt bồ câu ra ràng", "Pigeon young bird flesh skin and giblets", "Thịt và sản phẩm chế biến", List.of("thit bo cau ra rang", "pigeon young bird flesh skin and giblets"), 340, 17.5, 0.0, 30.0));
        items.add(food("Thịt chó sấn", "Dog meat", "Thịt và sản phẩm chế biến", List.of("thit cho san", "dog meat"), 338, 16.0, 0.0, 30.4));
        items.add(food("Thịt chó vai", "Dog, shoulder", "Thịt và sản phẩm chế biến", List.of("thit cho vai", "dog, shoulder"), 230, 18.0, 0.0, 17.6));
        items.add(food("Thịt cừu, nạc", "Mutton meat, lean", "Thịt và sản phẩm chế biến", List.of("thit cuu, nac", "mutton meat, lean"), 219, 16.4, 0.0, 17.0));
        items.add(food("Thịt dê, nạc", "Goat, meat, lean", "Thịt và sản phẩm chế biến", List.of("thit de, nac", "goat, meat, lean"), 122, 20.7, 0.0, 4.3));
        items.add(food("Thịt gà rừng", "Grouse field chicken", "Thịt và sản phẩm chế biến", List.of("thit ga rung", "grouse field chicken"), 141, 24.4, 0.0, 4.8));
        items.add(food("Thịt gà ta", "Chicken meat, average", "Thịt và sản phẩm chế biến", List.of("thit ga ta", "chicken meat, average"), 199, 20.3, 0.0, 13.1));
        items.add(food("Thịt gà tây", "Turkey raw flesh and skin giblets", "Thịt và sản phẩm chế biến", List.of("thit ga tay", "turkey raw flesh and skin giblets"), 218, 20.1, 0.0, 15.3));
        items.add(food("Thịt hươu", "Deer meat", "Thịt và sản phẩm chế biến", List.of("thit huou", "deer meat"), 94, 19.0, 0.0, 2.0));
        items.add(food("Thịt lợn mỡ", "Pork, lean and fat", "Thịt và sản phẩm chế biến", List.of("thit lon mo", "pork, lean and fat"), 394, 14.5, 0.0, 37.3));
        items.add(food("Thịt lợn nạc", "Pork, lean", "Thịt và sản phẩm chế biến", List.of("thit lon nac", "pork, lean"), 139, 19.0, 0.0, 7.0));
        items.add(food("Thịt lợn nửa nạc, nửa mỡ", "Pork, medium fat", "Thịt và sản phẩm chế biến", List.of("thit lon nua nac, nua mo", "pork, medium fat"), 260, 16.5, 0.0, 21.5));
        items.add(food("Thịt ngỗng", "Goose", "Thịt và sản phẩm chế biến", List.of("thit ngong", "goose"), 409, 14.0, 0.0, 39.2));
        items.add(food("Thịt ngựa", "Horse meat", "Thịt và sản phẩm chế biến", List.of("thit ngua", "horse meat"), 176, 21.5, 0.0, 10.0));
        items.add(food("Thịt thỏ nhà", "Rabbit meat, raw", "Thịt và sản phẩm chế biến", List.of("thit tho nha", "rabbit meat, raw"), 158, 21.5, 0.0, 8.0));
        items.add(food("Thịt thỏ rừng", "Hare rabbit (field or wild)", "Thịt và sản phẩm chế biến", List.of("thit tho rung", "hare rabbit (field or wild)"), 103, 23.5, 0.0, 1.0));
        items.add(food("Thịt trâu", "Buffalo meat, average", "Thịt và sản phẩm chế biến", List.of("thit trau", "buffalo meat, average"), 97, 20.4, 0.9, 1.4));
        items.add(food("Thịt trâu bắp", "Buffalo meat (shoulder)", "Thịt và sản phẩm chế biến", List.of("thit trau bap", "buffalo meat (shoulder)"), 115, 21.9, 0.0, 3.0));
        items.add(food("Thịt trâu cổ", "Buffalo meat, neck", "Thịt và sản phẩm chế biến", List.of("thit trau co", "buffalo meat, neck"), 112, 20.9, 0.0, 3.1));
        items.add(food("Thịt trâu đùi", "Buffalo meat, leg", "Thịt và sản phẩm chế biến", List.of("thit trau đui", "buffalo meat, leg"), 112, 21.2, 0.0, 3.0));
        items.add(food("Thịt trâu thăn", "Buffalo meat, lean (loin)", "Thịt và sản phẩm chế biến", List.of("thit trau than", "buffalo meat, lean (loin)"), 121, 22.8, 0.0, 3.3));
        items.add(food("Thịt vịt", "Duck meat, average", "Thịt và sản phẩm chế biến", List.of("thit vit", "duck meat, average"), 267, 17.8, 0.0, 21.8));
        items.add(food("Bầu dục bò", "Beef, kidney", "Thịt và sản phẩm chế biến", List.of("bau duc bo", "beef, kidney"), 67, 12.5, 0.3, 1.8));
        items.add(food("Bầu dục lợn", "Pork, kidney", "Thịt và sản phẩm chế biến", List.of("bau duc lon", "pork, kidney"), 81, 13.0, 0.3, 3.1));
        items.add(food("Bì lợn", "Pork skin", "Thịt và sản phẩm chế biến", List.of("bi lon", "pork skin"), 118, 23.3, 0.0, 2.7));
        items.add(food("Chân giò lợn", "Pork, leg", "Thịt và sản phẩm chế biến", List.of("chan gio lon", "pork, leg"), 230, 15.7, 0.0, 18.6));
        items.add(food("Dạ dày bò", "Stomach, beef", "Thịt và sản phẩm chế biến", List.of("da day bo", "stomach, beef"), 97, 14.8, 0.0, 4.2));
        items.add(food("Dạ dày lợn", "Stomach, hog", "Thịt và sản phẩm chế biến", List.of("da day lon", "stomach, hog"), 85, 14.6, 0.0, 2.9));
        items.add(food("Đầu bò", "Head beef (without tongue, brain, ears).", "Thịt và sản phẩm chế biến", List.of("đau bo", "head beef (without tongue, brain, ears)."), 185, 18.1, 0.0, 12.5));
        items.add(food("Đầu lợn", "Hog, head", "Thịt và sản phẩm chế biến", List.of("đau lon", "hog, head"), 335, 13.4, 0.0, 31.3));
        items.add(food("Đuôi bò", "Beef, tail", "Thịt và sản phẩm chế biến", List.of("đuoi bo", "beef, tail"), 137, 19.7, 0.0, 6.5));
        items.add(food("Đuôi lợn", "Hog, tail", "Thịt và sản phẩm chế biến", List.of("đuoi lon", "hog, tail"), 467, 10.8, 0.0, 47.1));
        items.add(food("Gan bò", "Beef, liver", "Thịt và sản phẩm chế biến", List.of("gan bo", "beef, liver"), 109, 17.4, 3.0, 3.1));
        items.add(food("Gan gà", "Chicken liver", "Thịt và sản phẩm chế biến", List.of("gan ga", "chicken liver"), 111, 18.2, 2.0, 3.4));
        items.add(food("Gan lợn", "Pork liver", "Thịt và sản phẩm chế biến", List.of("gan lon", "pork liver"), 116, 18.8, 2.0, 3.6));
        items.add(food("Gan vịt", "Duck liver", "Thịt và sản phẩm chế biến", List.of("gan vit", "duck liver"), 122, 17.1, 2.8, 4.7));
        items.add(food("Gân chân bò", null, "Thịt và sản phẩm chế biến", List.of("gan chan bo"), 124, 30.2, 0.0, 0.3));
        items.add(food("Lưỡi bò", "Beef tongue", "Thịt và sản phẩm chế biến", List.of("luoi bo", "beef tongue"), 164, 13.6, 0.2, 12.1));
        items.add(food("Lưỡi lợn", "Hog, tongue", "Thịt và sản phẩm chế biến", List.of("luoi lon", "hog, tongue"), 178, 14.2, 1.4, 12.8));
        items.add(food("Lòng lợn (ruột già)", "Hog, intestine large raw", "Thịt và sản phẩm chế biến", List.of("long lon (ruot gia)", "hog, intestine large raw"), 167, 6.9, 0.8, 15.1));
        items.add(food("Lòng lợn (ruột non)", "Hog intestine small raw without fat", "Thịt và sản phẩm chế biến", List.of("long lon (ruot non)", "hog intestine small raw without fat"), 44, 7.2, 0.8, 1.3));
        items.add(food("Mề gà", "Chicken gizzard", "Thịt và sản phẩm chế biến", List.of("me ga", "chicken gizzard"), 99, 21.3, 0.6, 1.3));
        items.add(food("óc bò", "Brain beef", "Thịt và sản phẩm chế biến", List.of("oc bo", "brain beef"), 124, 9.0, 0.5, 9.5));
        items.add(food("óc lợn", "Hog brain", "Thịt và sản phẩm chế biến", List.of("oc lon", "hog brain"), 123, 9.0, 0.4, 9.5));
        items.add(food("Phổi bò", "Beef, lung", "Thịt và sản phẩm chế biến", List.of("phoi bo", "beef, lung"), 103, 15.2, 0.0, 4.7));
        items.add(food("Phổi lợn", "Hog lung, raw", "Thịt và sản phẩm chế biến", List.of("phoi lon", "hog lung, raw"), 92, 14.8, 0.0, 3.6));
        items.add(food("Sườn lợn", "Pork, ribs", "Thịt và sản phẩm chế biến", List.of("suon lon", "pork, ribs"), 187, 17.9, 0.0, 12.8));
        items.add(food("Tai lợn", "Hog ears", "Thịt và sản phẩm chế biến", List.of("tai lon", "hog ears"), 126, 21.0, 1.3, 4.1));
        items.add(food("Tim bò", "Beef, heart", "Thịt và sản phẩm chế biến", List.of("tim bo", "beef, heart"), 89, 15.0, 0.6, 3.0));
        items.add(food("Tim gà", "Chicken heart", "Thịt và sản phẩm chế biến", List.of("tim ga", "chicken heart"), 114, 16.0, 0.0, 5.5));
        items.add(food("Tim lợn", "Hog heart", "Thịt và sản phẩm chế biến", List.of("tim lon", "hog heart"), 94, 15.1, 1.2, 3.2));
        items.add(food("Tiết bò", "Beef, blood", "Thịt và sản phẩm chế biến", List.of("tiet bo", "beef, blood"), 75, 18.0, 0.4, 0.2));
        items.add(food("Tiết lợn luộc", "Hog blood, boiled", "Thịt và sản phẩm chế biến", List.of("tiet lon luoc", "hog blood, boiled"), 44, 10.7, 0.0, 0.1));
        items.add(food("Tiết lợn sống", "Hog blood, raw", "Thịt và sản phẩm chế biến", List.of("tiet lon song", "hog blood, raw"), 25, 5.7, 0.2, 0.1));
        items.add(food("Tủy xương bò", "Beef bone marrow", "Thịt và sản phẩm chế biến", List.of("tuy xuong bo", "beef bone marrow"), 814, 1.1, 0.0, 89.9));
        items.add(food("Tủy xương lợn", "Hog, bone marrow", "Thịt và sản phẩm chế biến", List.of("tuy xuong lon", "hog, bone marrow"), 749, 2.3, 0.0, 82.2));
        items.add(food("Ba tê", "Pa tª", "Thịt và sản phẩm chế biến", List.of("ba te", "pa tª"), 326, 10.8, 15.4, 24.6));
        items.add(food("Chả lợn", "Pork, mince fat meat grilled", "Thịt và sản phẩm chế biến", List.of("cha lon", "pork, mince fat meat grilled"), 517, 10.8, 5.1, 50.4));
        items.add(food("Chả quế lợn", "Pork, cinnamon mince grilled", "Thịt và sản phẩm chế biến", List.of("cha que lon", "pork, cinnamon mince grilled"), 416, 16.2, 0.0, 39.0));
        items.add(food("Dăm bông lợn", "Ham, pork", "Thịt và sản phẩm chế biến", List.of("dam bong lon", "ham, pork"), 318, 23.0, 0.3, 25.0));
        items.add(food("Dồi lợn", "Blood mix-pudding with viscera in large intestine", "Thịt và sản phẩm chế biến", List.of("doi lon", "blood mix-pudding with viscera in large intestine"), 114, 12.4, 0.0, 7.1));
        items.add(food("Giò bò", "Beef dumpling", "Thịt và sản phẩm chế biến", List.of("gio bo", "beef dumpling"), 357, 13.8, 0.0, 33.5));
        items.add(food("Giò lụa", "Pork, mince lean meat steamed", "Thịt và sản phẩm chế biến", List.of("gio lua", "pork, mince lean meat steamed"), 136, 21.5, 0.0, 5.5));
        items.add(food("Giò thủ lợn", "Pork, head meat, steamed", "Thịt và sản phẩm chế biến", List.of("gio thu lon", "pork, head meat, steamed"), 553, 16.0, 0.0, 54.3));
        items.add(food("Lạp xường", "Chinese sausage", "Thịt và sản phẩm chế biến", List.of("lap xuong", "chinese sausage"), 585, 20.8, 1.7, 55.0));
        items.add(food("Nem chạo", null, "Thịt và sản phẩm chế biến", List.of("nem chao"), 153, 16.6, 6.9, 6.5));
        items.add(food("Nem chua", "Pork mince, fermented", "Thịt và sản phẩm chế biến", List.of("nem chua", "pork mince, fermented"), 137, 21.7, 4.3, 3.7));
        items.add(food("Ruốc thịt lợn", null, "Thịt và sản phẩm chế biến", List.of("ruoc thit lon"), 369, 46.6, 0.0, 20.3));
        items.add(food("Thịt bò khô", "Dried beef", "Thịt và sản phẩm chế biến", List.of("thit bo kho", "dried beef"), 239, 51.0, 5.2, 1.6));
        items.add(food("Thịt trâu khô", "Buffalo meat, dried", "Thịt và sản phẩm chế biến", List.of("thit trau kho", "buffalo meat, dried"), 226, 50.4, 0.0, 2.7));
        items.add(food("Xúc xích", "Pork sausage", "Thịt và sản phẩm chế biến", List.of("xuc xich", "pork sausage"), 535, 27.2, 0.0, 47.4));
        items.add(food("Bột cóc", "Toad meat powder", "Thịt và sản phẩm chế biến", List.of("bot coc", "toad meat powder"), 342, 55.4, 0.0, 13.4));
        items.add(food("Châu chấu", "Locust", "Thịt và sản phẩm chế biến", List.of("chau chau", "locust"), 130, 24.3, 0.0, 3.6));
        items.add(food("ếch (thịt đùi)", "Frog", "Thịt và sản phẩm chế biến", List.of("ech (thit đui)", "frog"), 90, 20.0, 0.0, 1.1));
        items.add(food("Nhộng", "Silk worm", "Thịt và sản phẩm chế biến", List.of("nhong", "silk worm"), 111, 13.0, 0.0, 6.5));
        items.add(food("Lòng gà (cả bộ)", "Chicken giblets", "Thịt và sản phẩm chế biến", List.of("long ga (ca bo)", "chicken giblets"), 119, 17.9, 1.8, 4.5));
        items.add(food("Cá bống", "Goby, gudgeon", "Thủy sản và sản phẩm chế biến", List.of("ca bong", "goby, gudgeon"), 70, 15.8, 0.0, 0.8));
        items.add(food("Cá chày", "Pond fish", "Thủy sản và sản phẩm chế biến", List.of("ca chay", "pond fish"), 113, 20.1, 0.0, 3.6));
        items.add(food("Cá chép", "Carp", "Thủy sản và sản phẩm chế biến", List.of("ca chep", "carp"), 96, 16.0, 0.0, 3.6));
        items.add(food("Cá dưa", "Conger pike", "Thủy sản và sản phẩm chế biến", List.of("ca dua", "conger pike"), 115, 17.6, 0.0, 5.0));
        items.add(food("Cá dầu", null, "Thủy sản và sản phẩm chế biến", List.of("ca dau"), 96, 18.9, 0.0, 2.3));
        items.add(food("Cá diếc", "Mullet, harder", "Thủy sản và sản phẩm chế biến", List.of("ca diec", "mullet, harder"), 87, 17.7, 0.0, 1.8));
        items.add(food("Cá đao", "Sawfish, wolfherring", "Thủy sản và sản phẩm chế biến", List.of("ca đao", "sawfish, wolfherring"), 94, 18.3, 0.0, 2.3));
        items.add(food("Cá đé", "Chinese herring", "Thủy sản và sản phẩm chế biến", List.of("ca đe", "chinese herring"), 83, 18.7, 0.0, 0.9));
        items.add(food("Cá đối", "Mullet, gray mullet", "Thủy sản và sản phẩm chế biến", List.of("ca đoi", "mullet, gray mullet"), 108, 19.5, 0.0, 3.3));
        items.add(food("Cá đồng tiền", "Goby", "Thủy sản và sản phẩm chế biến", List.of("ca đong tien", "goby"), 98, 20.1, 0.0, 2.0));
        items.add(food("Cá hồi", "Salmon", "Thủy sản và sản phẩm chế biến", List.of("ca hoi", "salmon"), 136, 22.0, 0.0, 5.3));
        items.add(food("Cá khô (chim, thu, nụ, đé)", "Dried fish, miscellaneous", "Thủy sản và sản phẩm chế biến", List.of("ca kho (chim, thu, nu, đe)", "dried fish, miscellaneous"), 208, 43.3, 0.0, 3.9));
        items.add(food("Cá lác", null, "Thủy sản và sản phẩm chế biến", List.of("ca lac"), 71, 16.7, 0.0, 0.5));
        items.add(food("Cá mè", "Hypophthalmichthys, chub, dory, tench bream", "Thủy sản và sản phẩm chế biến", List.of("ca me", "hypophthalmichthys, chub, dory, tench bream"), 144, 15.4, 0.0, 9.1));
        items.add(food("Cá mòi", "Sardin", "Thủy sản và sản phẩm chế biến", List.of("ca moi", "sardin"), 124, 17.5, 0.0, 6.0));
        items.add(food("Cá mỡ", null, "Thủy sản và sản phẩm chế biến", List.of("ca mo"), 151, 16.8, 0.0, 9.3));
        items.add(food("Cá mối", null, "Thủy sản và sản phẩm chế biến", List.of("ca moi"), 116, 22.1, 0.0, 3.1));
        items.add(food("Cá nạc", "Fish low fat", "Thủy sản và sản phẩm chế biến", List.of("ca nac", "fish low fat"), 80, 17.5, 0.0, 1.1));
        items.add(food("Cá ngừ", "Flying fish, tuna", "Thủy sản và sản phẩm chế biến", List.of("ca ngu", "flying fish, tuna"), 87, 21.0, 0.0, 0.3));
        items.add(food("Cá nục", "Scad, anchovy", "Thủy sản và sản phẩm chế biến", List.of("ca nuc", "scad, anchovy"), 111, 20.2, 0.0, 3.3));
        items.add(food("Cá phèn", "Goatfish, surmullet, red mullet", "Thủy sản và sản phẩm chế biến", List.of("ca phen", "goatfish, surmullet, red mullet"), 104, 15.9, 0.0, 4.5));
        items.add(food("Cá quả", "Fish, snake head", "Thủy sản và sản phẩm chế biến", List.of("ca qua", "fish, snake head"), 97, 18.2, 0.0, 2.7));
        items.add(food("Cá rô đồng", "Anabas", "Thủy sản và sản phẩm chế biến", List.of("ca ro đong", "anabas"), 126, 19.1, 0.0, 5.5));
        items.add(food("Cá rô phi", "Tilapia, African carp", "Thủy sản và sản phẩm chế biến", List.of("ca ro phi", "tilapia, african carp"), 100, 19.7, 0.0, 2.3));
        items.add(food("Cá thờn bơn (cá bơn)", "Flounder, sole, turbot", "Thủy sản và sản phẩm chế biến", List.of("ca thon bon (ca bon)", "flounder, sole, turbot"), 73, 17.4, 0.0, 0.4));
        items.add(food("Cá thu", "Mackerel, codfish, kingfish", "Thủy sản và sản phẩm chế biến", List.of("ca thu", "mackerel, codfish, kingfish"), 166, 18.2, 0.0, 10.3));
        items.add(food("Cá thu đao", null, "Thủy sản và sản phẩm chế biến", List.of("ca thu đao"), 156, 20.0, 0.0, 8.4));
        items.add(food("Cá trạch (cá chạch)", "Loach", "Thủy sản và sản phẩm chế biến", List.of("ca trach (ca chach)", "loach"), 110, 20.4, 0.0, 3.2));
        items.add(food("Cá trắm cỏ", "Carp, amur", "Thủy sản và sản phẩm chế biến", List.of("ca tram co", "carp, amur"), 91, 17.0, 0.0, 2.6));
        items.add(food("Cá trê", "Catfish, silurus, sheatfish, hito", "Thủy sản và sản phẩm chế biến", List.of("ca tre", "catfish, silurus, sheatfish, hito"), 173, 16.5, 0.0, 11.9));
        items.add(food("Cá trích", "Herring", "Thủy sản và sản phẩm chế biến", List.of("ca trich", "herring"), 166, 17.7, 0.0, 10.6));
        items.add(food("Cá trôi", "Major carp, mud carp; cirrhina molitorella", "Thủy sản và sản phẩm chế biến", List.of("ca troi", "major carp, mud carp; cirrhina molitorella"), 127, 18.8, 0.0, 5.7));
        items.add(food("Cua bể", "Crab, sea water", "Thủy sản và sản phẩm chế biến", List.of("cua be", "crab, sea water"), 103, 17.5, 7.0, 0.6));
        items.add(food("Cua đồng", "Crab, fresh water", "Thủy sản và sản phẩm chế biến", List.of("cua đong", "crab, fresh water"), 87, 12.3, 2.0, 3.3));
        items.add(food("ghẹ", "Crab", "Thủy sản và sản phẩm chế biến", List.of("ghe", "crab"), 54, 11.9, 0.0, 0.7));
        items.add(food("Hải sâm", "Sea slug, sea cucumber", "Thủy sản và sản phẩm chế biến", List.of("hai sam", "sea slug, sea cucumber"), 90, 21.5, 0.2, 0.3));
        items.add(food("Hến", "Clam", "Thủy sản và sản phẩm chế biến", List.of("hen", "clam"), 45, 4.5, 5.1, 0.7));
        items.add(food("Lươn", "Eel, silver - pike", "Thủy sản và sản phẩm chế biến", List.of("luon", "eel, silver - pike"), 180, 18.4, 0.2, 11.7));
        items.add(food("Mực khô", "Dried cuttle fish, squid", "Thủy sản và sản phẩm chế biến", List.of("muc kho", "dried cuttle fish, squid"), 291, 60.1, 2.5, 4.5));
        items.add(food("Mực tươi", "Cuttle fish, raw (Squid)", "Thủy sản và sản phẩm chế biến", List.of("muc tuoi", "cuttle fish, raw (squid)"), 73, 16.3, 0.0, 0.9));
        items.add(food("ốc bươu", "Snail medium - size, edible", "Thủy sản và sản phẩm chế biến", List.of("oc buou", "snail medium - size, edible"), 84, 11.1, 8.3, 0.7));
        items.add(food("ốc đá", "Marble snail, edible", "Thủy sản và sản phẩm chế biến", List.of("oc đa", "marble snail, edible"), 63, 11.2, 3.9, 0.3));
        items.add(food("ốc nhồi", "Snail large, edible", "Thủy sản và sản phẩm chế biến", List.of("oc nhoi", "snail large, edible"), 84, 11.9, 7.6, 0.7));
        items.add(food("ốc vặn", "Helix", "Thủy sản và sản phẩm chế biến", List.of("oc van", "helix"), 72, 12.2, 4.3, 0.7));
        items.add(food("Rạm (muối, đồ)", "Small sea - crab bicled, steamed", "Thủy sản và sản phẩm chế biến", List.of("ram (muoi, đo)", "small sea - crab bicled, steamed"), 83, 14.2, 0.0, 2.9));
        items.add(food("Rạm tươi", "Small sea - crab", "Thủy sản và sản phẩm chế biến", List.of("ram tuoi", "small sea - crab"), 77, 12.9, 0.0, 2.8));
        items.add(food("Rươi", "Tylorhynchus sinensis", "Thủy sản và sản phẩm chế biến", List.of("ruoi", "tylorhynchus sinensis"), 89, 12.4, 0.0, 4.4));
        items.add(food("Sò", "Oyster", "Thủy sản và sản phẩm chế biến", List.of("so", "oyster"), 78, 9.5, 4.9, 2.3));
        items.add(food("Tép gạo", "Tiny shrimp", "Thủy sản và sản phẩm chế biến", List.of("tep gao", "tiny shrimp"), 58, 11.7, 0.0, 1.2));
        items.add(food("Tép khô", "Tiny shrimp, dried", "Thủy sản và sản phẩm chế biến", List.of("tep kho", "tiny shrimp, dried"), 269, 59.8, 0.7, 3.0));
        items.add(food("Tôm biển", "Sea shrimp, sea-water shrimp", "Thủy sản và sản phẩm chế biến", List.of("tom bien", "sea shrimp, sea-water shrimp"), 82, 17.6, 0.9, 0.9));
        items.add(food("Tôm đồng", "Fresh-water shrimp", "Thủy sản và sản phẩm chế biến", List.of("tom đong", "fresh-water shrimp"), 90, 18.4, 0.0, 1.8));
        items.add(food("Tôm khô", "Shrimp, dried", "Thủy sản và sản phẩm chế biến", List.of("tom kho", "shrimp, dried"), 347, 75.6, 2.5, 3.8));
        items.add(food("Trai", "Manodonta", "Thủy sản và sản phẩm chế biến", List.of("trai", "manodonta"), 38, 4.6, 2.5, 1.1));
        items.add(food("Bánh phồng tôm rán", "Deep fried shrimp paste", "Thủy sản và sản phẩm chế biến", List.of("banh phong tom ran", "deep fried shrimp paste"), 676, 1.6, 34.1, 59.2));
        items.add(food("Bánh phồng tôm sống", "Shrimp paste", "Thủy sản và sản phẩm chế biến", List.of("banh phong tom song", "shrimp paste"), 381, 3.4, 75.3, 7.4));
        items.add(food("Bột cá", "Fish flour with bones", "Thủy sản và sản phẩm chế biến", List.of("bot ca", "fish flour with bones"), 323, 71.2, 3.0, 2.9));
        items.add(food("Ruốc cá quả", "Shredded snake-head fish, salted and dried", "Thủy sản và sản phẩm chế biến", List.of("ruoc ca qua", "shredded snake-head fish, salted and dried"), 312, 65.7, 3.0, 4.1));
        items.add(food("Ruốc tôm", "Shredded shrimp, salted and dried", "Thủy sản và sản phẩm chế biến", List.of("ruoc tom", "shredded shrimp, salted and dried"), 305, 65.5, 3.7, 3.1));
        items.add(food("Trứng gà", "Hen egg, raw, whole", "Trứng và sản phẩm chế biến", List.of("trung ga", "hen egg, raw, whole"), 166, 14.8, 0.5, 11.6));
        items.add(food("Lòng đỏ trứng gà", "Hen egg, yolk", "Trứng và sản phẩm chế biến", List.of("long đo trung ga", "hen egg, yolk"), 327, 13.6, 1.0, 29.8));
        items.add(food("Lòng trắng trứng gà", "Hen egg, white", "Trứng và sản phẩm chế biến", List.of("long trang trung ga", "hen egg, white"), 46, 10.3, 1.0, 0.1));
        items.add(food("Trứng vịt", "Duck egg, whole", "Trứng và sản phẩm chế biến", List.of("trung vit", "duck egg, whole"), 184, 13.0, 1.0, 14.2));
        items.add(food("Lòng đỏ trứng vịt", "Duck egg, yolk", "Trứng và sản phẩm chế biến", List.of("long đo trung vit", "duck egg, yolk"), 364, 13.6, 4.8, 32.3));
        items.add(food("Lòng trắng trứng vịt", "Duck egg, white", "Trứng và sản phẩm chế biến", List.of("long trang trung vit", "duck egg, white"), 47, 10.7, 0.8, 0.1));
        items.add(food("Trứng chim cút", "Quail egg", "Trứng và sản phẩm chế biến", List.of("trung chim cut", "quail egg"), 154, 13.1, 0.4, 11.1));
        items.add(food("Trứng cá", "Fish roe", "Trứng và sản phẩm chế biến", List.of("trung ca", "fish roe"), 171, 20.5, 0.0, 9.9));
        items.add(food("Trứng cá muối", "Fish caviar, black and red, granule", "Trứng và sản phẩm chế biến", List.of("trung ca muoi", "fish caviar, black and red, granule"), 274, 24.6, 3.5, 17.9));
        items.add(food("Trứng vịt lộn", "Duck egg, embryonated", "Trứng và sản phẩm chế biến", List.of("trung vit lon", "duck egg, embryonated"), 182, 13.6, 4.0, 12.4));
        items.add(food("Bột trứng", "Chicken egg powder", "Trứng và sản phẩm chế biến", List.of("bot trung", "chicken egg powder"), 563, 44.0, 1.8, 42.2));
        items.add(food("Sữa bò tươi", "Milk cow, fresh (fluid)", "Sữa và sản phẩm chế biến", List.of("sua bo tuoi", "milk cow, fresh (fluid)"), 74, 3.9, 4.8, 4.4));
        items.add(food("Sữa dê tươi", "Milk goat's, whole", "Sữa và sản phẩm chế biến", List.of("sua de tuoi", "milk goat's, whole"), 69, 3.5, 4.5, 4.1));
        items.add(food("Sữa mẹ (sữa người)", "Breast milk (Human milk, whole).", "Sữa và sản phẩm chế biến", List.of("sua me (sua nguoi)", "breast milk (human milk, whole)."), 61, 1.5, 7.0, 3.0));
        items.add(food("Sữa chua (từ sữa bò)", "Yogurt (whole milk)", "Sữa và sản phẩm chế biến", List.of("sua chua (tu sua bo)", "yogurt (whole milk)"), 61, 3.3, 3.6, 3.7));
        items.add(food("Sữa chua vớt béo", "Yogurt, chocolate, nonfat milk", "Sữa và sản phẩm chế biến", List.of("sua chua vot beo", "yogurt, chocolate, nonfat milk"), 103, 3.5, 22.3, 0.0));
        items.add(food("Sữa bột toàn phần", "Milk powder, whole", "Sữa và sản phẩm chế biến", List.of("sua bot toan phan", "milk powder, whole"), 494, 27.0, 38.0, 26.0));
        items.add(food("Sữa bột tách béo", "Skimmed milk powder", "Sữa và sản phẩm chế biến", List.of("sua bot tach beo", "skimmed milk powder"), 357, 35.0, 52.0, 1.0));
        items.add(food("Sữa đặc có đường Việt Nam", "Milk condensed, sweetened", "Sữa và sản phẩm chế biến", List.of("sua đac co đuong viet nam", "milk condensed, sweetened"), 336, 8.1, 56.0, 8.8));
        items.add(food("Pho mát", "Cheese (whole fat)", "Sữa và sản phẩm chế biến", List.of("pho mat", "cheese (whole fat)"), 380, 25.5, 0.0, 30.9));
        items.add(food("Chuối nước đường", "Banana, canned, sweetened", "Đồ hộp", List.of("chuoi nuoc đuong", "banana, canned, sweetened"), 58, 0.5, 13.9, 0.0));
        items.add(food("Dưa chuột hộp", "Cucumber (canned)", "Đồ hộp", List.of("dua chuot hop", "cucumber (canned)"), 8, 0.3, 1.2, 0.2));
        items.add(food("Dứa hộp", "Pineapple, canned, sweetened", "Đồ hộp", List.of("dua hop", "pineapple, canned, sweetened"), 53, 0.4, 12.7, 0.1));
        items.add(food("Lạc chao dầu", "Peanut, oil fried", "Đồ hộp", List.of("lac chao dau", "peanut, oil fried"), 680, 25.7, 10.3, 59.5));
        items.add(food("Mắc coọc nước đường", "Pyrus pachis in syrup", "Đồ hộp", List.of("mac cooc nuoc đuong", "pyrus pachis in syrup"), 56, 0.2, 13.7, 0.0));
        items.add(food("Mận nước đường", "Plum, canned, sweetened", "Đồ hộp", List.of("man nuoc đuong", "plum, canned, sweetened"), 64, 0.4, 15.4, 0.1));
        items.add(food("Mứt bí ngô", "Dried preserved squash", "Đồ hộp", List.of("mut bi ngo", "dried preserved squash"), 198, 0.5, 49.1, 0.0));
        items.add(food("Mứt cam có vỏ", "Orange marmalade, jellies", "Đồ hộp", List.of("mut cam co vo", "orange marmalade, jellies"), 218, 0.4, 54.2, 0.0));
        items.add(food("Mứt chuối", "Banana jam", "Đồ hộp", List.of("mut chuoi", "banana jam"), 218, 0.7, 53.9, 0.0));
        items.add(food("Mứt dứa", "Pineapple jam", "Đồ hộp", List.of("mut dua", "pineapple jam"), 208, 0.5, 51.5, 0.0));
        items.add(food("Mứt đu đủ", "Papaya jam", "Đồ hộp", List.of("mut đu đu", "papaya jam"), 178, 0.4, 44.1, 0.0));
        items.add(food("Nhãn nước đường", "Longan, canned, sweetened", "Đồ hộp", List.of("nhan nuoc đuong", "longan, canned, sweetened"), 62, 0.5, 15.0, 0.0));
        items.add(food("Nước dứa hộp", "Pineapple juice", "Đồ hộp", List.of("nuoc dua hop", "pineapple juice"), 53, 0.4, 12.6, 0.1));
        items.add(food("Vải nước đường", "Litchi, canned, sweetened", "Đồ hộp", List.of("vai nuoc đuong", "litchi, canned, sweetened"), 60, 0.4, 14.7, 0.0));
        items.add(food("Cá thu hộp", "Mackerel, canned", "Đồ hộp", List.of("ca thu hop", "mackerel, canned"), 207, 24.8, 0.0, 12.0));
        items.add(food("Cá trích hộp", "Herring, canned", "Đồ hộp", List.of("ca trich hop", "herring, canned"), 233, 22.3, 3.5, 14.4));
        items.add(food("Thịt bò hộp", "Beef, canned", "Đồ hộp", List.of("thit bo hop", "beef, canned"), 251, 16.4, 0.0, 20.6));
        items.add(food("Thịt gà hộp", "Chicken, canned", "Đồ hộp", List.of("thit ga hop", "chicken, canned"), 273, 17.0, 0.0, 22.8));
        items.add(food("Thịt lợn hộp", "Pork, canned", "Đồ hộp", List.of("thit lon hop", "pork, canned"), 344, 17.3, 2.7, 29.3));
        items.add(food("Thịt lợn, thịt bò xay hộp", "Pork and beef, minced canned", "Đồ hộp", List.of("thit lon, thit bo xay hop", "pork and beef, minced canned"), 244, 16.0, 0.0, 20.0));
        items.add(food("Thịt vịt hầm", "Duck, stewed meat", "Đồ hộp", List.of("thit vit ham", "duck, stewed meat"), 224, 19.6, 0.0, 16.2));
        items.add(food("Bánh bích cốt", "Whole wheat rusk", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("banh bich cot", "whole wheat rusk"), 346, 12.3, 71.3, 1.3));
        items.add(food("Bánh bích quy", "Biscuits", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("banh bich quy", "biscuits"), 376, 8.8, 75.1, 4.5));
        items.add(food("Bánh chả", "Sweet meat pie in lumps", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("banh cha", "sweet meat pie in lumps"), 395, 3.4, 80.5, 6.6));
        items.add(food("Bánh con cá", "Small biscuits, fish figured", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("banh con ca", "small biscuits, fish figured"), 368, 7.5, 79.6, 2.2));
        items.add(food("Bánh đậu xanh", "Mungbean cake", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("banh đau xanh", "mungbean cake"), 416, 15.6, 62.4, 11.5));
        items.add(food("Bánh kem xốp", "Wafers filled", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("banh kem xop", "wafers filled"), 492, 8.3, 60.7, 24.0));
        items.add(food("Bánh khảo chay", "Rice cake, plain", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("banh khao chay", "rice cake, plain"), 376, 3.2, 90.2, 0.3));
        items.add(food("Bánh quế", "Cinnamon waffle (roll)", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("banh que", "cinnamon waffle (roll)"), 435, 8.3, 76.4, 10.7));
        items.add(food("Bánh sô cô la", "Chocolate, filled", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("banh so co la", "chocolate, filled"), 449, 3.9, 68.8, 17.6));
        items.add(food("Bánh thỏi sô cô la", "Chocolate, sweet", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("banh thoi so co la", "chocolate, sweet"), 543, 4.9, 62.5, 30.4));
        items.add(food("Bánh trứng nhện", "Small biscuit", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("banh trung nhen", "small biscuit"), 369, 9.6, 74.2, 3.7));
        items.add(food("Bột ca cao", "Cocoa powder", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("bot ca cao", "cocoa powder"), 414, 19.6, 53.0, 13.7));
        items.add(food("Đường cát", "Refined sugar", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("đuong cat", "refined sugar"), 390, 0.0, 97.4, 0.0));
        items.add(food("Đường kính", "Granulated sugar", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("đuong kinh", "granulated sugar"), 397, 0.0, 99.3, 0.0));
        items.add(food("Kẹo bơ cứng", "Toffee, sweets", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("keo bo cung", "toffee, sweets"), 448, 2.1, 71.1, 17.2));
        items.add(food("Kẹo cà phê", "Coffee sweets", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("keo ca phe", "coffee sweets"), 378, 0.0, 91.5, 1.3));
        items.add(food("Kẹo cam chanh", "Sweets, caramel with citron, orange aroma", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("keo cam chanh", "sweets, caramel with citron, orange aroma"), 377, 0.0, 93.1, 0.5));
        items.add(food("Kẹo dừa mềm", "Sweets with coconut aroma", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("keo dua mem", "sweets with coconut aroma"), 415, 0.6, 75.6, 12.2));
        items.add(food("Kẹo dứa mềm", "Pineapple sweets candy", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("keo dua mem", "pineapple sweets candy"), 415, 0.6, 75.6, 12.2));
        items.add(food("Kẹo lạc", "Peanut candy", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("keo lac", "peanut candy"), 449, 10.3, 64.8, 16.5));
        items.add(food("Kẹo Pastille (kẹo ngậm bạc hà)", "Menthol pastille", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("keo pastille (keo ngam bac ha)", "menthol pastille"), 356, 5.2, 83.8, 0.0));
        items.add(food("Kẹo sô cô la", "Sweets with chocolate", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("keo so co la", "sweets with chocolate"), 388, 1.6, 85.1, 4.6));
        items.add(food("Kẹo sữa", "Sweets with milk", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("keo sua", "sweets with milk"), 390, 2.9, 83.0, 5.2));
        items.add(food("Kẹo vừng viên", "Sesame candy", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("keo vung vien", "sesame candy"), 417, 2.8, 85.9, 6.9));
        items.add(food("Mạch nha", "Malt", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("mach nha", "malt"), 331, 0.2, 82.5, 0.0));
        items.add(food("Mật ong", "Honey", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("mat ong", "honey"), 327, 0.4, 81.3, 0.0));
        items.add(food("Mứt lạc", "Peanut sugar (Jam)", "Đồ ngọt (đường, bánh, mứt, kẹo)", List.of("mut lac", "peanut sugar (jam)"), 431, 5.4, 82.9, 8.6));
        items.add(food("Cary bột", "Cari powder (Mix, turmeric, red pepper and other spices)", "Gia vị, nước chấm", List.of("cary bot", "cari powder (mix, turmeric, red pepper and other spices)"), 283, 8.2, 46.0, 7.3));
        items.add(food("Gừng khô (bột)", "Ginger root, dried powder", "Gia vị, nước chấm", List.of("gung kho (bot)", "ginger root, dried powder"), 323, 9.1, 58.3, 5.9));
        items.add(food("Gừng tươi", "Ginger root, fresh", "Gia vị, nước chấm", List.of("gung tuoi", "ginger root, fresh"), 29, 0.4, 5.1, 0.8));
        items.add(food("Hạt tiêu", "Peppercorn, seeds", "Gia vị, nước chấm", List.of("hat tieu", "peppercorn, seeds"), 231, 7.0, 34.1, 7.4));
        items.add(food("Muối", "Table salt", "Gia vị, nước chấm", List.of("muoi", "table salt"), 0, 0.0, 0.0, 0.0));
        items.add(food("Nghệ khô, bột", "Turmeric rhizome, dried powder", "Gia vị, nước chấm", List.of("nghe kho, bot", "turmeric rhizome, dried powder"), 295, 7.8, 43.8, 9.9));
        items.add(food("Nghệ tươi", "Turmeric, rhizome, fresh", "Gia vị, nước chấm", List.of("nghe tuoi", "turmeric, rhizome, fresh"), 25, 1.1, 4.4, 0.3));
        items.add(food("ớt khô bột", "Red pepper, dried powder", "Gia vị, nước chấm", List.of("ot kho bot", "red pepper, dried powder"), 227, 15.6, 31.8, 4.2));
        items.add(food("Riềng", "Alpinia root, fresh", "Gia vị, nước chấm", List.of("rieng", "alpinia root, fresh"), 26, 0.3, 2.5, 0.0));
        items.add(food("Magi", "Soybean sauce", "Gia vị, nước chấm", List.of("magi", "soybean sauce"), 65, 10.5, 5.6, 0.1));
        items.add(food("Mắm tôm đặc", "Shrimp sauce concentrate", "Gia vị, nước chấm", List.of("mam tom đac", "shrimp sauce concentrate"), 73, 14.8, 0.0, 1.5));
        items.add(food("Mắm tôm loãng", "Shrimp sauce, diluted", "Gia vị, nước chấm", List.of("mam tom loang", "shrimp sauce, diluted"), 44, 7.0, 2.1, 0.8));
        items.add(food("Mắm tép chua", "Tiny shrimp, sour sauce", "Gia vị, nước chấm", List.of("mam tep chua", "tiny shrimp, sour sauce"), 68, 8.7, 5.5, 1.2));
        items.add(food("Nước mắm cá (loại đặc biệt)", "Fish - sauce (super quality).", "Gia vị, nước chấm", List.of("nuoc mam ca (loai đac biet)", "fish - sauce (super quality)."), 60, 15.0, 0.0, 0.0));
        items.add(food("Nước mắm cá loại I", "Fish sauce, grade I", "Gia vị, nước chấm", List.of("nuoc mam ca loai i", "fish sauce, grade i"), 28, 7.1, 0.0, 0.0));
        items.add(food("Nước mắm loại II", "Fish sauce, grade II", "Gia vị, nước chấm", List.of("nuoc mam loai ii", "fish sauce, grade ii"), 21, 5.2, 0.0, 0.0));
        items.add(food("Nước mắm cá", "Fish sauce, ready-to-serve", "Gia vị, nước chấm", List.of("nuoc mam ca", "fish sauce, ready-to-serve"), 35, 5.1, 3.6, 0.01));
        items.add(food("Nước mắm cô", "Fish sauce, concentrated", "Gia vị, nước chấm", List.of("nuoc mam co", "fish sauce, concentrated"), 131, 32.8, 0.0, 0.0));
        items.add(food("Tương ngô", "Soybean sauce with rice and maize", "Gia vị, nước chấm", List.of("tuong ngo", "soybean sauce with rice and maize"), 75, 3.9, 14.5, 0.1));
        items.add(food("Tương nếp", "Soybean sauce with glutinous rice", "Gia vị, nước chấm", List.of("tuong nep", "soybean sauce with glutinous rice"), 86, 4.3, 15.7, 0.7));
        items.add(food("Tương ớt", "Red pepper sauce concentrate", "Gia vị, nước chấm", List.of("tuong ot", "red pepper sauce concentrate"), 37, 0.5, 7.6, 0.5));
        items.add(food("Xì dầu", "Soybean sauce", "Gia vị, nước chấm", List.of("xi dau", "soybean sauce"), 53, 6.3, 6.8, 0.04));
        items.add(food("Sốt mayonnaise", "Mayonnaise", "Gia vị, nước chấm", List.of("sot mayonnaise", "mayonnaise"), 701, 0.0, 0.1, 77.8));
        items.add(food("Bia (cồn: 4,5 g)", "Beer light (4,5 % Alcohol)", "Nước giải khát, bia, rượu", List.of("bia (con: 4,5 g)", "beer light (4,5 % alcohol)"), 11, 0.5, 2.3, 0.0));
        items.add(food("Cô nhắc (cồn 32 g)", "Cognac", "Nước giải khát, bia, rượu", List.of("co nhac (con 32 g)", "cognac"), 0, 0.0, 0.0, 0.0));
        items.add(food("Cốc tai (cồn 13 g)", "Cocktail, vermouth sweet", "Nước giải khát, bia, rượu", List.of("coc tai (con 13 g)", "cocktail, vermouth sweet"), 63, 0.0, 15.7, 0.0));
        items.add(food("Coca cola", "Coca Cola", "Nước giải khát, bia, rượu", List.of("coca cola"), 42, 0.0, 10.4, 0.0));
        items.add(food("Nước cam tươi", "Orange juice, fresh", "Nước giải khát, bia, rượu", List.of("nuoc cam tuoi", "orange juice, fresh"), 23, 0.7, 4.5, 0.2));
        items.add(food("Nước dừa non tươi", "Coconut milk, immature", "Nước giải khát, bia, rượu", List.of("nuoc dua non tuoi", "coconut milk, immature"), 21, 0.4, 4.8, 0.0));
        items.add(food("Nước ép cà chua", "Tomato juice", "Nước giải khát, bia, rượu", List.of("nuoc ep ca chua", "tomato juice"), 19, 0.8, 2.6, 0.6));
        items.add(food("Nước khoáng", "Mineral water", "Nước giải khát, bia, rượu", List.of("nuoc khoang", "mineral water"), 0, 0.0, 0.0, 0.0));
        items.add(food("Nước quít tươi", "Mandarins juice (fresh)", "Nước giải khát, bia, rượu", List.of("nuoc quit tuoi", "mandarins juice (fresh)"), 24, 0.4, 5.1, 0.2));
        items.add(food("Rượu cam, chanh (cồn 24,2 g)", "Liqueur, orange flavor", "Nước giải khát, bia, rượu", List.of("ruou cam, chanh (con 24,2 g)", "liqueur, orange flavor"), 0, 0.0, 0.0, 0.0));
        items.add(food("Rượu nếp (80g/ 24 ml) (cồn 5 g)", "Rice glutinous (Alcohol fermentation rice 80 g water 24 ml)", "Nước giải khát, bia, rượu", List.of("ruou nep (80g/ 24 ml) (con 5 g)", "rice glutinous (alcohol fermentation rice 80 g water 24 ml)"), 167, 4.0, 37.7, 0.0));
        items.add(food("Rượu trắng (cồn 39 g)", "Vodka", "Nước giải khát, bia, rượu", List.of("ruou trang (con 39 g)", "vodka"), 273, 0.0, 0.0, 0.0));
        items.add(food("Rượu vang đỏ (cồn 9,5 g)", "Red wine", "Nước giải khát, bia, rượu", List.of("ruou vang đo (con 9,5 g)", "red wine"), 9, 0.2, 2.0, 0.0));
        items.add(food("Rượu vang trắng (cồn 9,5 g)", "White wine", "Nước giải khát, bia, rượu", List.of("ruou vang trang (con 9,5 g)", "white wine"), 1, 0.1, 0.2, 0.0));
        items.add(food("Rượu vang trắng ngọt (cồn 10.2 g)", "White wine, sweet", "Nước giải khát, bia, rượu", List.of("ruou vang trang ngot (con 10.2 g)", "white wine, sweet"), 24, 0.2, 5.9, 0.0));
        items.add(food("Rượu Whisky (cồn 35,2 g)", "Whisky liqueur", "Nước giải khát, bia, rượu", List.of("ruou whisky (con 35,2 g)", "whisky liqueur"), 0, 0.0, 0.0, 0.0));
        return items;
    }

    private static FoodItem food(
            String nameVi,
            String nameEn,
            String category,
            List<String> aliases,
            int caloriesKcal,
            double protein,
            double carb,
            double fat) {
        return FoodItem.builder()
                .nameVi(nameVi)
                .nameEn(nameEn)
                .category(category)
                .aliases(aliases)
                .servingSizeG(BigDecimal.valueOf(100))
                .calories(BigDecimal.valueOf(caloriesKcal))
                .protein(BigDecimal.valueOf(protein))
                .carb(BigDecimal.valueOf(carb))
                .fat(BigDecimal.valueOf(fat))
                .isComposite(false)
                .source(SOURCE)
                .build();
    }
}
