spring.application.name=nutrican-pt-api

spring.config.import=optional:file:../.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=${SERVER_PORT:8080}

minio.url=http://localhost:${MINIO_API_PORT:9000}
minio.access-key=${MINIO_ROOT_USER}
minio.secret-key=${MINIO_ROOT_PASSWORD}
minio.bucket-name=${MINIO_BUCKET_NAME}

ai.ollama.base-url=http://localhost:${OLLAMA_PORT:11434}
ai.ollama.default-model=${OLLAMA_MODEL:llava}

ai.resnet.base-url=http://localhost:${AI_RESNET_PORT:8000}
ai.resnet.enabled=true
ai.resnet.confidence-threshold=0.25
ai.recognition.confidence-threshold=0.25

app.security.jwt.secret-key=${JWT_SECRET_KEY}
app.security.jwt.expiration=${JWT_EXPIRATION_MS}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springdoc=DEBUG
