import api from './api';

export const workspaceService = {
    getClients: (params) => api.get('/workspace/clients', { params }),
    getPendingLogs: (params) => api.get('/workspace/diet-logs/pending', { params }),
    reviewLog: (id, data) => api.put(`/workspace/diet-logs/${id}/review`, data),
    getClientProgress: (clientId, params) => api.get(`/workspace/progress/${clientId}`, { params }),
    assignClient: (clientId) => api.post(`/workspace/clients/${clientId}/assign`),
    getStats: () => api.get('/workspace/stats'),
    getAlerts: () => api.get('/workspace/alerts'),
    submitBlindEstimate: (logId, data) => api.put(`/workspace/diet-logs/${logId}/blind-estimate`, data),
    getPtRblStats: () => api.get('/workspace/rbl/stats'),
    updateHireRequest: (clientId, action) => api.put(`/workspace/clients/${clientId}/hire-request`, null, { params: { action } }),
    createMealPlan: (payload) => api.post('/workspace/meal-plans', payload),
    updateMealPlan: (clientId, payload) => api.put(`/workspace/meal-plans/${clientId}`, payload),
    publishMealPlan: (planId) => api.post(`/workspace/meal-plans/${planId}/publish`),
    getClientMealPlan: (clientId, weekStart) => api.get(`/workspace/meal-plans/${clientId}`, { params: { weekStart } }),
    setClientMacroTarget: (clientId, data) => api.put(`/workspace/clients/${clientId}/macro-target`, data),
    setCoachingEvaluation: (clientId, data) => api.put(`/workspace/clients/${clientId}/coaching-evaluation`, data),
    reviewMealPlanSuggestion: (id, data) => api.put(`/workspace/meal-plan-suggestions/${id}`, data),
    getPendingMealPlanSuggestions: (clientId) => api.get(`/workspace/clients/${clientId}/meal-plan-suggestions`),
    listSelfPlanSubmissions: () => api.get('/workspace/self-plan-submissions'),
    reviewSelfPlanSubmission: (id, data) => api.put(`/workspace/self-plan-submissions/${id}`, data),
    createWeeklySummary: (data) => api.post('/workspace/weekly-summary', data),
    requestEndCoaching: (clientId) => api.post(`/workspace/clients/${clientId}/end-coaching`),
    confirmEndCoaching: (clientId) => api.put(`/workspace/clients/${clientId}/end-coaching/confirm`),
    markSessionDone: (sessionId) => api.post(`/workspace/sessions/${sessionId}/mark-done`),
    getSessionDisputes: (params = {}) => api.get('/workspace/session-disputes', { params }),
    replySessionDispute: (id, data) => api.post(`/workspace/session-disputes/${id}/messages`, data),
    getChatContext: (clientId) => api.get(`/workspace/clients/${clientId}/chat-context`),
    getClientProfile: (clientId) => api.get(`/workspace/clients/${clientId}/profile`),
    getClientDayPlan: (clientId, date) => api.get(`/workspace/clients/${clientId}/day-plan`, { params: { date } }),
    getClientDietSummary: (clientId, date) => api.get(`/workspace/clients/${clientId}/diet-summary`, { params: { date } }),
    getClientDayTimeline: (clientId, date) => api.get(`/workspace/clients/${clientId}/day-timeline`, { params: { date } }),
    updateClientProfile: (clientId, data) => api.put(`/workspace/clients/${clientId}/profile`, data),
    createClient: (data) => api.post('/workspace/clients', data),
    saveAsTemplate: (data) => api.post('/workspace/templates', data),
    getTemplates: () => api.get('/workspace/templates'),
    applyTemplateToClient: (clientId, templateId, data) => api.post(`/workspace/clients/${clientId}/apply-template/${templateId}`, data),
};
